---
title: "ONLY CODE"
output: pdf_document
date: "2023-08-23"
---

```{r c1}
library(dplyr)
rm(list=ls())
gridd<-expand.grid(prev.STH=c(0.01,0.03),schools=c(10,20),n.days=c(1,2 ), n.slide=c(1,2 ),pooln1=10, CV.i=1.5,mu=1000, CV.d=0.75,  pooln2=25, CV.d.10=0.6,CV.d.25=0.5, CV.s=0.25, plotss=FALSE, TPR=0.88*0.88,TNR=0.97*0.97, n.s=100, misclasifica=FALSE)

gridd$nnn=gridd$schools*gridd$n.s

gridd$dataset<-1:nrow(gridd)

gridd$name<-paste0("Dataset: ", gridd$dataset,"Shools: ",gridd$schools,". STH Prev:",gridd$prev.STH,". Days:",gridd$n.days,". Slides:",gridd$n.slide)
gridd$daysXsample<-gridd$n.days*gridd$n.slide
gridd<-gridd[order(gridd$daysXsample),]

gridd<-gridd[order(gridd$prev.STH,gridd$schools,gridd$n.days,gridd$n.slide),]

gridd$scenario<-gridd$Scenario<-1:nrow(gridd)


gridd$Info_level<-ifelse(gridd$daysXsample==1,"Low",ifelse(gridd$daysXsample==2,"Low Medium",ifelse(gridd$daysXsample==3,"Medium",ifelse(gridd$daysXsample==4,"Medium High",ifelse(gridd$daysXsample==6,"High", ifelse(gridd$daysXsample==9,"Very High",NA))))))
grid.sim<-vector(mode='list', length=nrow(gridd))
for (ji in 1:nrow(gridd)) {
grid.sim[[ji]]<-gridd[ji,]
}
library(dplyr)
library(tidyverse)
library(Hmisc)
library(vcd)
library(VGAM)
reps=1:100

gridd.print<-subset(gridd,select = -c(plotss,TPR,TNR, misclasifica,dataset,scenario,Info_level, pooln2))
```


```{r TabDGM}

gridd.print<-subset(gridd,select =c(Scenario,prev.STH,schools, n.days,n.slide, mu,pooln1,CV.i,CV.d,CV.d.10,CV.s,n.s,nnn))

#colnames(gridd.print)%>%clipr::write_clip()
colnames(gridd.print)<-c("Scenario",
                           "$\\pi_{schools}$",
                           "$n_{schools}$",
                           "$n_{days}$",
                           "$n_{slides}$",
                           "$\\mu$",                           
                           "$\\eta$",
                           "$CV_i$",
                           "$CV_d^{1}$",
                           "$CV_d^{10}$",
                           "$CV_s$",
                           "n.s",
                           "N")
 

library(flextable)

if(knitr::is_latex_output()) {
gridd.print%>%kableExtra::kable(row.names = FALSE,caption = "Considered scenarios as data generating mechanism for the simulation study.", escape = F)%>% kableExtra::add_header_above(c("Scenarios" = 5, "Assumptions" = 2, "Agregattion parameters" = 4, "Sample size" = 2))%>% kableExtra::kable_styling(font_size = 8, latex_options = c("striped","HOLD_position")) %>% kableExtra::add_footnote(escape = F, c("$\\pi_{schools}$: true Prevalence for each school, $n_{schools}$ is the number of schools; $n_{days}$ is the number of $days$ where test are conducted, $n_{slides}$ is the number $slides$ collected for each day; $\\mu$ is the population mean EPG, $\\eta$ is the the number of subjects for each pool; $CV_i$, $CV_d^{1}$, $CV_d^{10}$, $CV_s$ are the Coefficient of Variation related to subject, related to $days$ in each subject sample, related to $days$ in each pool sample, related to each slide, respectively; $n.s$ is the number of subjects per $schools$, and $N$ is the total number of subjects in the whole population."), threeparttable = TRUE, notation="none") 


} else if (!knitr::is_latex_output() ) {
gridd.print %>% flextable::flextable()%>%autofit()%>%flextable::set_caption("Considered scenarios as data generating mechanism for the simulation study.")
}

```






```{r c2cambio, eval=F, include=F}
#params=grid.sim
start_time <- Sys.time()
params=grid.sim;
datatest<-vector(mode='list', length=length(params))
simSTH <- function( params = list()) {

for (ji in 1:length(params)) {

  nnn=params[[ji]][["nnn"]]
  schools=params[[ji]][["schools"]]
  pool=params[[ji]][["pooln1"]]
  prev.STH =params[[ji]][["prev.STH"]]
  var.STH=params[[ji]][["var.STH"]]


  n.s=nnn/schools  #subjects in each school
  S.label<-1:schools
  datatest[[ji]]$School.name<-rep(S.label,each=n.s)
  datatest[[ji]]<-as.data.frame(datatest[[ji]])
  #colnames(datatest[[ji]])<-"School.name"
  datatest[[ji]]$n<-nrow(datatest[[ji]])

  datatest[[ji]]$dataset<-params[[ji]][["dataset"]]
  datatest[[ji]]$ind.n<-NA
  datatest[[ji]]$ind.n<- rep(1:n.s,each=1, times=schools)

  n.pool<-1:(n.s/pool)
  datatest[[ji]]$pool10<-rep(n.pool,each=pool)

  

  datatest[[ji]]$prev<-params[[ji]][["prev.STH"]]
 
  datatest[[ji]]$DX<-rbinom(n=nrow(datatest[[ji]]),size=1,prob= datatest[[ji]]$prev)
 

  datatest[[ji]]<-datatest[[ji]]%>%group_by(School.name,ind.n) %>%dplyr::mutate(ID.sub = cur_group_id())

  n.s=params[[ji]]$n.s
  n.days=params[[ji]]$n.days
  n.slide=params[[ji]]$n.slide
  nnn=params[[ji]]$nnn
  TPR=params[[ji]]$TPR
  TNR=params[[ji]]$TNR
  schools=params[[ji]]$schools
  ####Check-up: n.s should be a multiple of ss1 and ss2 ()
  ss1=n.s/params[[ji]]$pooln1 #Number of subsets for pool1
  ss2=n.s/params[[ji]]$pooln2 #Number of subsets for pool2
  if (!n.s%%ss1==0 & !n.s%%ss2==0 ) {
    warning("Number of subjects in dataset should be a multiple of the numbers of the pooled samples (pooln1 and pooln2)")
    stop()
  }
  if (!n.s%%ss1==0 ) {
    warning("Number of subjects in each school should be a multiple of the numbers of the pooled samples (pooln1)")
    stop()
  }
  if (!n.s%%ss2==0 ) {
    warning("Number of subjects in each shool  should be a multiple of the numbers of the pooled samples (pooln2)")
    stop()
  }
  ##  1 Variability in mean egg intensity between individuals, gamma dist, params$CV.i=1.5
  # The DGM can explored a grid with different values of K (or params$CV.i)
  #number of subjects
  Ki=1/params[[ji]]$CV.i^2
  datatest[[ji]]$Mu<- params[[ji]]$mu
  datatest[[ji]]$CV.d<- params[[ji]]$CV.d


  #replicating the datasets n.days times.
  datatest[[ji]]<- map(seq_len(n.days),~datatest[[ji]]) %>% bind_rows(.id="day")
  #datatest<-datatest.copy
  datatest[[ji]]<-datatest[[ji]][order(datatest[[ji]]$School.name,datatest[[ji]]$ind.n,datatest[[ji]]$day),]
  datatest[[ji]]$day<-as.numeric(datatest[[ji]]$day)

  #replicating the datasets n.slide times.
  datatest[[ji]]<- map(seq_len(n.slide),~datatest[[ji]]) %>% bind_rows(.id="sample")
  datatest[[ji]]<-datatest[[ji]][order(datatest[[ji]]$School.name,datatest[[ji]]$ind.n,datatest[[ji]]$day,datatest[[ji]]$sample),]
  datatest[[ji]]$sample<-as.numeric(datatest[[ji]]$sample)


  # Mid: for the days
  #nnn*n.days*n.slide

  datatest[[ji]]$NegDX<-ifelse(datatest[[ji]]$DX==1,0,1)

  prueb3<-datatest[[ji]]%>%group_by(School.name,day,sample) %>%  dplyr::summarise(across(DX, sum))
  prueb4<-datatest[[ji]]%>%group_by(School.name,day,sample) %>%  dplyr::summarise(across(NegDX, sum))
  colnames(prueb3)<-c("School.name","day","sample","Sick")
  colnames(prueb4)<-c("School.name","day","sample","Healthy")
  datatest[[ji]]<-merge(datatest[[ji]],prueb3,by = c("School.name","day","sample"))
  datatest[[ji]]<-merge(datatest[[ji]],prueb4,by = c("School.name","day","sample"))
  datatest[[ji]]$IDID<-1:nrow(datatest[[ji]])
  min.inf=0  #to produced a shifted gamma

  datatest[[ji]]<-datatest[[ji]][order(datatest[[ji]]$ID.sub,datatest[[ji]]$day,datatest[[ji]]$sample),]
  datatest[[ji]]$Mi<-datatest[[ji]]$Mid1<-datatest[[ji]]$Mids1<-NA
  for (ii in 1:(nnn)) {
    #o#o#       ii=1
    x.i = n.days * n.slide * (ii - 1) + 1 #BEGINING OF THE SUBJECT LINE
    x.f = x.i + n.days * n.slide - 1 #END OF THE SUBJECT LINE

    ###################### Mean=shape*scale, shape=Mean/scale
    datatest[[ji]]$Mi[datatest[[ji]]$ID.sub==ii] <- ifelse(
      mean(datatest[[ji]]$DX[datatest[[ji]]$ID.sub==ii]) == 1,
      rep(rgamma(1, shape = Ki, scale = (params[[ji]]$mu-min.inf)/Ki),
          each = 1,
          times = n.days * n.slide),
      rep(0, each = 1, times = n.days * n.slide))
    for (dd in 1:n.days) {
      #o#o#             dd=2
      x.d = x.i + n.slide * (dd - 1) #-1
      #x.d.f = x.i + n.days * dd - 1
      x.d.f = x.d + n.slide - 1
      datatest[[ji]]$Mid1[x.d:x.d.f] = rep(
        rgamma(1,shape = params[[ji]]$CV.d ^ -2,
               scale = datatest[[ji]]$Mi[x.d:x.d.f] * params[[ji]]$CV.d ^ 2),
        each = 1,times = n.slide)

      for (ss in 1:n.slide) {
        #o#o# ss=1
        datatest[[ji]]$Mids1[x.d + ss - 1] = rgamma(1,shape = params[[ji]]$CV.d ^ -2,
                                                    scale = datatest[[ji]]$Mid1[x.d + ss - 1] * params[[ji]]$CV.d ^ 2)
      }
    }
  }

  hey<-datatest[[ji]]%>%group_by(School.name,day,sample, pool10) %>%dplyr::mutate(ID = cur_group_id())
  temp<-hey%>%group_by(ID)%>%dplyr::summarise(Mids10=mean(Mids1))
  datatest[[ji]]<-merge(hey,temp, by="ID")

  # Mids: for the samples

  mids.count.error<-0




  if (params[[ji]][["misclasifica"]] ) {
    datatest[[ji]] <-
      datatest[[ji]] %>% mutate(TP.ideal = round(Sick * TPR),
                                TN.ideal = round(Healthy * TNR))
    datatest[[ji]] <-
      datatest[[ji]] %>% mutate(FN.ideal = Sick - TP.ideal,
                                FP.ideal = Healthy - TN.ideal)
    datatest[[ji]] <-
      datatest[[ji]] %>% mutate(sens.ideal = TP.ideal / Sick, spec.ideal = TN.ideal /
                                  Healthy) #Only to check accuracy is ok
    datatest[[ji]]$DX.Miss <- datatest[[ji]]$DX



    for (SSS in 1:schools) {
      # Choose the ID of the missclasified subjects for each shcool
      subconj <- subset(datatest[[ji]], School.name == SSS)
      suj.0.ID <- subconj$IDID[subconj$DX == 0] #All N (Negatives)
      suj.1.ID <- subconj$IDID[subconj$DX == 1] #All P (Positives)
      ind.FP <-
        sample(suj.0.ID, subconj$FP.ideal[1], replace = FALSE) #Sample w/o replace FP-times
      ind.FN <-
        sample(suj.1.ID, subconj$FN.ideal[1], replace = FALSE) #Sample w/o replace FN-times
      datatest[[ji]]$DX.Miss[datatest[[ji]]$IDID %in% ind.FP] <-
        rep(1, each = 1, times = length(ind.FP)) #FP:0 is replaced with 1
      datatest[[ji]]$DX.Miss[datatest[[ji]]$IDID %in% ind.FN] <-
        rep(0, each = 1, times = length(ind.FN)) #FN:1 is replaced with 0
    }

    #Introduce FP: Introducing missclasification
    #Increase FN (to decrease sensitivity): using a ZIP
    datatest[[ji]]$Class2x2.a.ideal <-
      ifelse(((datatest[[ji]]$DX.Miss == datatest[[ji]]$DX)), "T", "F")
    datatest[[ji]]$Class2x2.b.ideal <-
      ifelse(datatest[[ji]]$DX.Miss == 1, "P", "N")
    datatest[[ji]]$Class2x2.ideal <-
      paste0(datatest[[ji]]$Class2x2.a, datatest[[ji]]$Class2x2.b)


    datatest[[ji]]$TRUE.PREV.DX.Miss <-
      100 * sum((
        datatest[[ji]] %>% group_by(ID.sub) %>% dplyr::summarise(cases = dplyr::first(DX.Miss))
      )$cases) / nrow(datatest[[ji]])

    mids.count.error <- 5
    datatest[[ji]]$count1 <-
      ifelse(datatest[[ji]]$Class2x2.ideal == "FP",
             rpois(1,  lambda = (datatest[[ji]]$Mids1 +
                                   mids.count.error)),
             rpois(1,  lambda = (datatest[[ji]]$Mids1)))
  }
  ttemp<-datatest[[ji]]%>%group_by(ID.sub)%>%dplyr::summarise(cases=dplyr::first(DX))
  datatest[[ji]]$TRUE.PREV.DX<- sum(ttemp$cases)/nrow(ttemp)







    datatest[[ji]]$count1<-rpois(nrow(datatest[[ji]]),  lambda=(datatest[[ji]]$Mids1 ))
    datatest[[ji]]$count10<-rpois(nrow(datatest[[ji]]), lambda=datatest[[ji]]$Mids10)

    temp.10<-datatest[[ji]]%>%group_by(School.name,pool10)%>%dplyr::summarise(count10.mean=round(mean(count10),digits=0))
    datatest[[ji]]<-merge(datatest[[ji]],temp.10, by=c("School.name","pool10"))
    datatest[[ji]]<-subset(datatest[[ji]],select=-count10)
    #asas<-datatest[[ji]]
    datatest[[ji]]<-dplyr::rename(datatest[[ji]],count10=count10.mean)
  datatest[[ji]]$TestR1<-ifelse(datatest[[ji]]$count1==0,0,1)

  #count1.mean

  datatest[[ji]]$TestR10<-ifelse(datatest[[ji]]$count10==0,0,1)

  datatest[[ji]]$Class2x2.a<-ifelse(((datatest[[ji]]$TestR1==datatest[[ji]]$DX)),"T","F")
  datatest[[ji]]$Class2x2.b<-ifelse(datatest[[ji]]$TestR1==1,"P","N")
  datatest[[ji]]$Class2x2<-paste0(datatest[[ji]]$Class2x2.a,datatest[[ji]]$Class2x2.b)

  if (params[[ji]][["misclasifica"]] ) {
  datatest[[ji]]<-subset(datatest[[ji]],select = -c(Class2x2.a,Class2x2.b,Class2x2, Class2x2.a.ideal,Class2x2.b.ideal))}


  datatest[[ji]]<-select(datatest[[ji]],-prev)

  temp.1<-datatest[[ji]]%>%group_by(ID.sub)%>%dplyr::summarise(count1.mean=round(mean(count1),digits=0))
  temp.10<-datatest[[ji]]%>%group_by(School.name,pool10)%>%dplyr::summarise(count10.mean=round(mean(count10),digits=0))

  datatest[[ji]]<-merge(datatest[[ji]],temp.1, by="ID.sub")
  datatest[[ji]]<-merge(datatest[[ji]],temp.10, by=c("School.name","pool10"))


  var.labels = c(ID="Identifier for each School.name,day,sample and pool10",
                 ID.sub="Unique identifier for each subject",
                 sample="Sample number",
                 day="Day number",
                 Mu="Mean EPG by Country or Province",
                 School.name="School number",
                 ind.n="Subject ID per school (not unique)",
                 pool10="Pool ID",
                 DX="True Diagnostic status",
                 DX.Miss="Diagnostic status with missclasification",
                 Mi="Mean EPG in each subject",
                 Mids1="Mean EPG in each subject per day and sample",
                 Mids10="Mean EPG in each pool per day and sample",
                 count1="Count of EPG in thick smear by subject per day and sample",
                 count10="Count of EPG in thick smear by pool per day and sample",
                 TestR1="KK binary result by subject per day and sample",
                 TestR10="KK binary result by pool 10 per day and sample",
                 count1.mean="Average Count of EPG in thick smear by subject",
                 count10.mean="Average Count of EPG in thick smear by pool")

  label(datatest[[ji]]) <- as.list(var.labels[match(names(datatest[[ji]]), names(var.labels))])

  }

  return(datatest)
}


DF<-list()
reps=1:100
for (kk in 1:length(grid.sim)) {
  for (ii in reps) {
     DF[[grid.sim[[kk]][["name"]] ]][[ii]]<-simSTH(params = list(grid.sim[[kk]]))
  }
}
#DF[[grid.sim[[kk]][["name"]] ]]<-lapply(X = reps,FUN = simSTH,params = list(grid.sim[[kk]]))
end_time <- Sys.time()
end_time - start_time



################################HISTROGRAM########################
################################HISTROGRAM########################
################################HISTROGRAM########################
prev.list<-matrix(nrow=(100*nrow(gridd)), ncol=3);
qqq=100
  indd=16
for (indd in 1:nrow(gridd)) {
    for (qqq in 1:100) {
  prev.list[qqq+(indd-1)*100,1]<-DF[[indd]][[qqq]][[1]][["TRUE.PREV.DX"]][1]
  prev.list[qqq+(indd-1)*100,2]<-DF[[indd]][[qqq]][[1]][["dataset"]][1]
  prev.list[qqq+(indd-1)*100,3]<- grid.sim[[indd]][["prev.STH"]]
  }
}
  prev.list<-as.data.frame(  prev.list)
library(ggplot2)
ggplot(prev.list, aes(x=V1))+geom_histogram()
colnames(prev.list)<-c("TP","Dataset","OTP")
ggplot(prev.list, aes(x=TP))+geom_histogram()
hist(prev.list$TP, main="All prevalence for all Simulated data mechanism (Prevalence=0.01 and 0.03)")
################################HISTROGRAM########################
################################HISTROGRAM########################
################################HISTROGRAM########################




library(dplyr)
tempo<-vector(mode='list', length=nrow(gridd))

for (kk in 1:16) {
  #cat("Dataset number ");cat(kk, sep="\n")
  for (mm in reps) {
  tempo[[kk]][[mm]]<-DF[[grid.sim[[kk]][["name"]]]][[mm]][[1]]%>%dplyr::reframe(count1.n=max(count1),count10.mean.n=unique(count10.mean), School.name.n=unique(School.name), ID.sub.n=unique(ID.sub), DX.n=unique(DX),pool10.n=mean(pool10),day.n=max(day),sample.n=max(sample),n.n=unique(n),dataset.n=unique(dataset),ind.n.n=unique(ind.n),DX.n=unique(DX),Mu.n=unique(Mu),CV.d.n=unique(CV.d),NegDX.n=unique(NegDX),Sick.n=unique(Sick),Healthy.n=unique(Healthy),Mids1.n=mean(Mids1),Mid1.n=mean(Mid1),Mi.n=mean(Mi),Mids10.n=mean(Mids10),TRUE.PREV.DX.n=unique(TRUE.PREV.DX),TestR1.n=max(TestR1),TestR10.n=unique(TestR10), .by=ID.sub)
  }
}

aver<-list()
for (ggg in 1:16) {
  aver[[ggg]]<-table(tempo[[ggg]][[1]][["sample.n"]],tempo[[ggg]][[1]][["day.n"]])
}


library(prevalence)
DF3<-list()
for (kk in 1:length(DF)) {
  for (ii in reps) {
    DF3[[grid.sim[[kk]][["name"]] ]][[ii]]<-as.data.frame(DF[[kk]][[ii]][[1]])
  }
}
```


```{r c3cambio, eval=F, include=F}
TEMPO<-list()

for (kk in 1:length(DF)) {
  for (ii in reps) {
    TEMPO[[grid.sim[[kk]][["name"]] ]][[ii]]<-as.data.frame(tempo[[kk]][[ii]])
  }
}
dataDF=TEMPO
```






```{r fitmodel, eval=TRUE, include=TRUE, echo=FALSE, tidy=TRUE, cache=F}

library(formatR)
library(prevalence)



fit_models <- function(dataDF = DF,
                       gridsDF = grid.sim,
                       model = "") {
  if (model == "Bayesian Rogen-Gladen") {
    dffit <- vector(mode = 'list', length = length(grid.sim))
    fit <- vector(mode = 'list', length = length(grid.sim))
    model = "Bayesian Rogen-Gladen"
    for (kk in 1:length(grid.sim)) {
      #KK IS THE NUMBER SCENARIOS
      dffit[[kk]] <-
        data.frame(matrix(nrow = length(grid.sim), ncol = 17))
      colnames(dffit[[kk]]) <-
        c(
          "Scenario name",
          "prev.STH",
          "Scenario",
          "Dataset n",
          "Rep n",
          "model",
          "theta.sd",
          "theta",
          "theta.var",
          "theta.se",
          "LIC",
          "UIC",
          "iHPD90",
          "uHPD90",
          "iHPD95",
          "uHPD95",          
          "n"
        )
      for (ii in reps) {
        #REPS IS THE NUMBER OF REPETITION FOR EACH SCENARIO
        

        fit[[kk]][[ii]] <-
          prevalence::truePrev(x = sum(dataDF[[gridsDF[[kk]][["name"]]]][[ii]]$TestR1.n),
                               n = length(dataDF[[grid.sim[[kk]][["name"]]]][[ii]]$TestR1.n))
        as <- fit[[kk]][[ii]]
        CI90<- coda::HPDinterval(as.mcmc(c(as@mcmc[["TP"]][[1]],as@mcmc[["TP"]][[2]])), prob=0.9)
        CI95<- coda::HPDinterval(as.mcmc(c(as@mcmc[["TP"]][[1]],as@mcmc[["TP"]][[2]])), prob=0.95)


        dffit[[kk]][ii, ] <-
          c(
            name = gridsDF[[kk]][["name"]],
            prev.STH = gridsDF[[kk]][["prev.STH"]],
            Scenario = gridsDF[[kk]][["Scenario"]],
            dataset.n = kk,
            rep = ii,
            model = model,
            theta.sd = as.numeric(summary(as)$TP[3, 4]),
            theta = as.numeric(summary(as)$TP[3, 1]),
            theta.var = as.numeric(summary(as)$TP[3, 5]),
            theta.se = as.numeric(sqrt(summary(as)$TP[3, 5])),
            LIC = as.numeric(summary(as)$TP[3, 6]),
            UIC = as.numeric(summary(as)$TP[3, 7]),
            iHPD90 = CI90[1],
            uHPD90 = CI90[2],
            iHPD95 = CI95[1],
            uHPD95 = CI95[2],
            n = as@par[["n"]]
          )
      }
    }
    
  }
  
    else if (model == "Frequentist Gold-Standard") {
    dffit <- vector(mode = 'list', length = length(grid.sim))
    fit <- vector(mode = 'list', length = length(grid.sim))
    model = "Frequentist Gold-Standard"
    for (kk in 1:length(grid.sim)) {
      #KK IS THE NUMBER SCENARIOS
      dffit[[kk]] <-data.frame(matrix(nrow = length(grid.sim), ncol = 17))
      colnames(dffit[[kk]]) <-
        c(
          "Scenario name",
          "prev.STH",
          "Scenario",
          "Dataset n",
          "Rep n",
          "model",
          "theta.sd",
          "theta",
          "theta.var",
          "theta.se",
          "LIC",
          "UIC",
          "iHPD90",
          "uHPD90",
          "iHPD95",
          "uHPD95",          
          "n"
        )
      for (ii in reps) {
        #REPS IS THE NUMBER OF REPETITION FOR EACH SCENARIO
        

        fit[[kk]][[ii]] <-prevalence::propCI(x = sum(dataDF[[gridsDF[[kk]][["name"]]]][[ii]]$TestR1.n),
                               n = length(dataDF[[grid.sim[[kk]][["name"]]]][[ii]]$TestR1.n),method = "exact", level = 0.95, sortby = "level")
        as <- fit[[kk]][[ii]]
        dffit[[kk]][ii, ] <-
          c(
            name = gridsDF[[kk]][["name"]],
            prev.STH = gridsDF[[kk]][["prev.STH"]],
            Scenario = gridsDF[[kk]][["Scenario"]],
            dataset.n = kk,
            rep = ii,
            model = model,
            theta.sd = NA,
            theta = as.numeric(as$p),
            theta.var =NA ,
            theta.se = NA,
            LIC = as$lower,
            UIC = as$upper,
            iHPD90 = NA,
            uHPD90 = NA,
            iHPD95 = as$lower,
            uHPD95 = as$upper,
            n = as$n
          )
      }
    }
    
  }
  
  else if (model == "Bayesian Rogen-Gladen Pool") {
    model = "Bayesian Rogen-Gladen Pool"
    dffit <- vector(mode = 'list', length = length(grid.sim))
    for (kk in 1:length(grid.sim)) {
      #KK IS THE NUMBER SCENARIOS
      dffit[[kk]] <-
        data.frame(matrix(nrow = length(grid.sim), ncol = 17))
      fit <- vector(mode = 'list', length = length(grid.sim))
      colnames(dffit[[kk]]) <-
        c(
          "Scenario name",
          "prev.STH",
          "Scenario",
          "Dataset n",
          "Rep n",
          "model",
          "theta.sd",
          "theta",
          "theta.var",
          "theta.se",
          "LIC",
          "UIC",
          "iHPD90",
          "uHPD90",
          "iHPD95",
          "uHPD95",          
          "n"
        )
      for (ii in reps) {
        #REPS IS THE NUMBER OF REPETITION FOR EACH SCENARIO
        tempor <-
          cbind(
            TestR10 = dataDF[[gridsDF[[kk]][["name"]]]][[ii]]$TestR10,
            School.name = dataDF[[gridsDF[[kk]][["name"]]]][[ii]]$School.name,
            pool10 = dataDF[[gridsDF[[kk]][["name"]]]][[ii]]$pool10
          )
        
        
        v.tempor <-tempor %>% as.data.frame() %>% group_by(School.name, pool10) %>%
          dplyr::summarise(primero =dplyr::first(TestR10))
        fit[[kk]][[ii]] <-prevalence::truePrevPools(x = v.tempor$primero,
                                                    n = rep(10, each =
gridsDF[[kk]][["schools"]]*gridsDF[[kk]][["pooln1"]]))
        
        as <- fit[[kk]][[ii]]
        CI90<- coda::HPDinterval(as.mcmc(c(as@mcmc[["TP"]][[1]],as@mcmc[["TP"]][[2]])), prob=0.9)
        CI95<- coda::HPDinterval(as.mcmc(c(as@mcmc[["TP"]][[1]],as@mcmc[["TP"]][[2]])), prob=0.95)

        dffit[[kk]][ii, ] <-
          c(
            name = gridsDF[[kk]][["name"]],
            prev.STH = gridsDF[[kk]][["prev.STH"]],
            Scenario = gridsDF[[kk]][["Scenario"]],
            dataset.n = kk,
            rep = ii,
            model = model,
            theta.sd = as.numeric(summary(as)$TP[3, 4]),
            theta = as.numeric(summary(as)$TP[3, 1]),
            theta.var = as.numeric(summary(as)$TP[3, 5]),
            theta.se = as.numeric(sqrt(summary(as)$TP[3, 5])),
            LIC = as.numeric(summary(as)$TP[3, 6]),
            UIC = as.numeric(summary(as)$TP[3, 7]),
            iHPD90 = CI90[1],
            uHPD90 = CI90[2],
            iHPD95 = CI95[1],
            uHPD95 = CI95[2],
            n = dataDF[[gridsDF[[kk]][["name"]]]][[ii]]$n.n[1]
          )
      }
    }
    
  } else if (model == "Method of Moment Pool") {
    dffit <- vector(mode = 'list', length = length(grid.sim))
    for (kk in 1:length(grid.sim)) {
      #KK IS THE NUMBER SCENARIOS
      dffit[[kk]] <-
        data.frame(matrix(nrow = length(grid.sim), ncol = 17))
      colnames(dffit[[kk]]) <-
        c(
          "Scenario name",
          "prev.STH",
          "Scenario",
          "Dataset n",
          "Rep n",
          "model",
          "theta.sd",
          "theta",
          "theta.var",
          "theta.se",
          "LIC",
          "UIC",
          "iHPD90",
          "uHPD90",
          "iHPD95",
          "uHPD95",
          "n"
        )
      for (ii in reps) {
        #REPS IS THE NUMBER OF REPETITION FOR EACH SCENARIO
        EPG.rep = dataDF[[gridsDF[[kk]][["name"]]]][[ii]]$count10.mean.n *24
        School.rep = dataDF[[gridsDF[[kk]][["name"]]]][[ii]]$School.name.n
        n.day.rep <- gridsDF[[1]][["n.days"]]
        n.slide.rep <- gridsDF[[1]][["n.slide"]]
        m_j <- gridsDF[[kk]][["pooln1"]]
        
        True.Pre.MoM <-
          1 - dnbinom(
            0,
            mu = tapply(EPG.rep, School.rep, mean),
            size = tapply(EPG.rep, School.rep, mean) / ((
              m_j * tapply(EPG.rep, School.rep, var) / tapply(EPG.rep, School.rep, mean)
            ) - 24 / (n.day.rep * n.slide.rep) - 1)
          )
        True.Pre.MoM <- ifelse(True.Pre.MoM == 'NaN', 0, True.Pre.MoM)
        library("plotrix")
        SE.True.Pre.MoM <- std.error(as.vector(True.Pre.MoM))
        True.Pre.MoM <- mean(True.Pre.MoM)
        True.Pre.Obs <-
          tapply(dataDF[[gridsDF[[kk]][["name"]]]][[ii]]$TRUE.PREV.DX, School.rep, mean)
        SE.True.Pre.Obs <- std.error(as.vector(True.Pre.Obs))
        True.Pre.Obs <- mean(True.Pre.Obs)
        
        
        dffit[[kk]][ii, ] <-
          c(
            name = gridsDF[[kk]][["name"]],
            prev.STH = gridsDF[[kk]][["prev.STH"]],
            Scenario = gridsDF[[kk]][["Scenario"]],
            dataset.n = kk,
            rep = ii,
            model = model,
            theta.sd = sqrt(var(True.Pre.MoM)),
            theta = True.Pre.MoM,
            theta.var = var(True.Pre.MoM),
            theta.se = SE.True.Pre.MoM,
            #theta.obs=True.Pre.Obs,
            #theta.obs.var=var(True.Pre.Obs), theta.obs.se=SE.True.Pre.Obs,
            LIC = NA,
            UIC = NA,
            iHPD90 = NA,
            uHPD90 = NA,
            iHPD95 = NA,
            uHPD95 = NA,            
            n = dataDF[[gridsDF[[kk]][["name"]]]][[ii]]$n.n[1]
          )
      }
    }
  } else if (model == "Method of Moment") {
    dffit <- vector(mode = 'list', length = length(grid.sim))
    #24/(n.day*n.slide)
    for (kk in 1:length(grid.sim)) {
      #KK IS THE NUMBER SCENARIOS
      dffit[[kk]] <-
        data.frame(matrix(nrow = length(grid.sim), ncol = 17))
      colnames(dffit[[kk]]) <-
        c(
          "Scenario name",
          "prev.STH",
          "Scenario",
          "Dataset n",
          "Rep n",
          "model",
          "theta.sd",
          "theta",
          "theta.var",
          "theta.se",
          "LIC",
          "UIC",
          "iHPD90",
          "uHPD90",
          "iHPD95",
          "uHPD95",
          "n"
        )
      for (ii in reps) {
        #REPS IS THE NUMBER OF REPETITION FOR EACH SCENARIO
        EPG.rep = dataDF[[gridsDF[[kk]][["name"]]]][[ii]]$count1.n * 24
        School.rep = dataDF[[gridsDF[[kk]][["name"]]]][[ii]]$School.name.n
        n.day.rep <- gridsDF[[1]][["n.days"]]
        n.slide.rep <- gridsDF[[1]][["n.slide"]]
        True.Pre.MoM <-
          1 - dnbinom(
            0,
            mu = tapply(EPG.rep, School.rep, mean),
            size = tapply(EPG.rep, School.rep, mean) / ((
              tapply(EPG.rep, School.rep, var) / tapply(EPG.rep, School.rep, mean)
            ) - 24 / (n.day.rep * n.slide.rep) - 1)
          )

        True.Pre.MoM <- ifelse(True.Pre.MoM == 'NaN', 0, True.Pre.MoM)
        library("plotrix")
        SE.True.Pre.MoM <- std.error(as.vector(True.Pre.MoM))
        True.Pre.MoM <- mean(True.Pre.MoM)
        
        True.Pre.Obs <-
          tapply(dataDF[[gridsDF[[kk]][["name"]]]][[ii]]$TRUE.PREV.DX, School.rep, mean)
        SE.True.Pre.Obs <- std.error(as.vector(True.Pre.Obs))
        True.Pre.Obs <- mean(True.Pre.Obs)
        
        
        dffit[[kk]][ii, ] <-
          c(
            name = gridsDF[[kk]][["name"]],
            prev.STH = gridsDF[[kk]][["prev.STH"]],
            Scenario = gridsDF[[kk]][["Scenario"]],
            dataset.n = kk,
            rep = ii,
            model = model,
            theta.sd = sqrt(var(True.Pre.MoM)),
            theta = True.Pre.MoM,
            theta.var = var(True.Pre.MoM),
            theta.se = SE.True.Pre.MoM,
            LIC = NA,
            UIC = NA,
            iHPD90 = NA,
            uHPD90 = NA,
            iHPD95 = NA,
            uHPD95 = NA,            
            
            
            n = dataDF[[gridsDF[[kk]][["name"]]]][[ii]]$n.n[1]
          )
      }
    }
  }
  # Return relevant coefficients
  list(dffit)
}

```



```{rcambio, eval=F, include=F}
results1<-results2<-results3<-results4<-list()
library(coda)
results1<-fit_models(dataDF=TEMPO, gridsDF=grid.sim,   model= "Bayesian Rogen-Gladen")
results2<-fit_models(dataDF=TEMPO, gridsDF=grid.sim,   model="Bayesian Rogen-Gladen Pool")
```


```{r, cache=F}


results3<-fit_models(dataDF=TEMPO, gridsDF=grid.sim,   model="Method of Moment")
results4<-fit_models(dataDF=TEMPO, gridsDF=grid.sim,   model="Method of Moment Pool")
results5<-list()

```


```{r c5, cache=F}
result1<-results1[[1]]
```


```{r c6, cache=F}
result2<-results2[[1]]
```


```{r c7, cache=F}
result3<-results3[[1]]
```


```{r c8, cache=F}
result4<-results4[[1]]
```




```{r c9, cache=F}
names(result1)<-c(result1[[1]][["Scenario name"]][1],
                 result1[[2]][["Scenario name"]][1],
                 result1[[3]][["Scenario name"]][1],
                 result1[[4]][["Scenario name"]][1],
                 result1[[5]][["Scenario name"]][1],
                 result1[[6]][["Scenario name"]][1],
                 result1[[7]][["Scenario name"]][1],
                 result1[[8]][["Scenario name"]][1],
                 result1[[9]][["Scenario name"]][1],
                 result1[[10]][["Scenario name"]][1],
                 result1[[11]][["Scenario name"]][1],
                 result1[[12]][["Scenario name"]][1],
                 result1[[13]][["Scenario name"]][1],
                 result1[[14]][["Scenario name"]][1],
                 result1[[15]][["Scenario name"]][1],
                 result1[[16]][["Scenario name"]][1])
names(result2)<-c(result2[[1]][["Scenario name"]][1],
                  result2[[2]][["Scenario name"]][1],
                  result2[[3]][["Scenario name"]][1],
                  result2[[4]][["Scenario name"]][1],
                  result2[[5]][["Scenario name"]][1],
                  result2[[6]][["Scenario name"]][1],
                  result2[[7]][["Scenario name"]][1],
                  result2[[8]][["Scenario name"]][1],
                  result2[[9]][["Scenario name"]][1],
                  result2[[10]][["Scenario name"]][1],
                  result2[[11]][["Scenario name"]][1],
                  result2[[12]][["Scenario name"]][1],
                  result2[[13]][["Scenario name"]][1],
                  result2[[14]][["Scenario name"]][1],
                  result2[[15]][["Scenario name"]][1],
                  result2[[16]][["Scenario name"]][1])
names(result3)<-c(result3[[1]][["Scenario name"]][1],
                  result3[[2]][["Scenario name"]][1],
                  result3[[3]][["Scenario name"]][1],
                  result3[[4]][["Scenario name"]][1],
                  result3[[5]][["Scenario name"]][1],
                  result3[[6]][["Scenario name"]][1],
                  result3[[7]][["Scenario name"]][1],
                  result3[[8]][["Scenario name"]][1],
                  result3[[9]][["Scenario name"]][1],
                  result3[[10]][["Scenario name"]][1],
                  result3[[11]][["Scenario name"]][1],
                  result3[[12]][["Scenario name"]][1],
                  result3[[13]][["Scenario name"]][1],
                  result3[[14]][["Scenario name"]][1],
                  result3[[15]][["Scenario name"]][1],
                  result3[[16]][["Scenario name"]][1])
names(result4)<-c(result4[[1]][["Scenario name"]][1],
                  result4[[2]][["Scenario name"]][1],
                  result4[[3]][["Scenario name"]][1],
                  result4[[4]][["Scenario name"]][1],
                  result4[[5]][["Scenario name"]][1],
                  result4[[6]][["Scenario name"]][1],
                  result4[[7]][["Scenario name"]][1],
                  result4[[8]][["Scenario name"]][1],
                  result4[[9]][["Scenario name"]][1],
                  result4[[10]][["Scenario name"]][1],
                  result4[[11]][["Scenario name"]][1],
                  result4[[12]][["Scenario name"]][1],
                  result4[[13]][["Scenario name"]][1],
                  result4[[14]][["Scenario name"]][1],
                  result4[[15]][["Scenario name"]][1],
                  result4[[16]][["Scenario name"]][1])

for (kk in 1:16) {
  colnames(result1[[kk]])<-colnames(result2[[kk]])<-c("Scenario name",
"prev.STH",
"Scenario",
"Dataset n",
"Rep n",
"model",
"theta.sd",
"theta",
"theta.var",
"theta.se",
"LIC",
"UIC",
"iHPD90",
"uHPD90",
"iHPD95",
"uHPD95",
"n")

}

results.merged<-c(result1,result2,result3,result4)
relhaz <- do.call(
  rbind.data.frame,
  results.merged
)

row.names(relhaz) <- NULL


relhaz$prev.STH<-as.numeric(relhaz$prev.STH)
relhaz$theta.sd<-as.numeric(relhaz$theta.sd)
relhaz$theta<-as.numeric(relhaz$theta)
relhaz$theta.se<-as.numeric(relhaz$theta.se)
relhaz$theta.var<-as.numeric(relhaz$theta.var)
relhaz$LIC<-as.numeric(relhaz$LIC)
relhaz$UIC<-as.numeric(relhaz$UIC)
relhaz$iHPD90<-as.numeric(relhaz$iHPD90)
relhaz$uHPD90<-as.numeric(relhaz$uHPD90)
relhaz$iHPD95<-as.numeric(relhaz$iHPD95)
relhaz$uHPD95<-as.numeric(relhaz$uHPD95)
relhaz$n<-as.numeric(relhaz$n)
#relhaz$TP<-as.numeric(relhaz$TP)
relhaz$`Rep n`<-as.numeric(relhaz$`Rep n`)

```



```{r c10, tab.cap="Prevalence check-up", cache=F}
relhaz$model<-ifelse(relhaz$model=="Bayesian Rogen-Gladen","BRGI",ifelse(relhaz$model=="Bayesian Rogen-Gladen Pool","BRGP", ifelse(relhaz$model=="Method of Moment","MoM Ind",ifelse(relhaz$model=="Method of Moment Pool","MoM Pool",relhaz$model))))


relhaz$Schools<-ifelse(grepl("Shools: 10",relhaz$`Scenario name`),10,20)
relhaz$Days<-ifelse(grepl("Days:1",relhaz$`Scenario name`),1,2)
relhaz$Slides<-ifelse(grepl("Slides:1",relhaz$`Scenario name`),1,2)
relhaz$daysXslides<-relhaz$Days*relhaz$Slides


#chequear el orden de TP, y previas integraciones
prevalencias<-unique(relhaz$prev.STH)

for (ll in 1:length(unique(relhaz$prev.STH))) {
  assign(paste("simm.all", ll, sep=""), rsimsum::simsum(data =   subset(relhaz,prev.STH==prevalencias[1]), estvarname = "theta", se ="theta.se", true = relhaz$prev.STH[ll], methodvar = "model", ci.limits = c("LIC", "UIC"),x = TRUE,ref = "BRGI", by =c("Schools", "Days","Slides"), control=list(level=0.95 ) ) )
}

for (ll in 1:length(unique(relhaz$prev.STH))) {
  assign(paste("simm.all.HPD.90.", ll, sep=""), rsimsum::simsum(data =   subset(relhaz,prev.STH==prevalencias[1]), estvarname = "theta", se ="theta.se", true = relhaz$prev.STH[ll], methodvar = "model", ci.limits = c("iHPD90", "uHPD90"),x = TRUE,ref = "BRGI", by =c("Schools", "Days","Slides"), control=list(level=0.90 ) ))
}


simm.all.HPD.95.1<- rsimsum::simsum(data =   subset(relhaz,prev.STH==0.01), estvarname = "theta", se ="theta.se", true = 0.01, methodvar = "model", ci.limits = c("iHPD95", "uHPD95"),x = TRUE,ref = "BRGI", by =c("Schools", "Days","Slides"), control=list(level=0.95 ) )
simm.all.HPD.90.1<- rsimsum::simsum(data =   subset(relhaz,prev.STH==0.01), estvarname = "theta", se ="theta.se", true = 0.01, methodvar = "model", ci.limits = c("iHPD90", "uHPD90"),x = TRUE,ref = "BRGI", by =c("Schools", "Days","Slides"), control=list(level=0.90 ) )
simm.all.HPD.95.2<- rsimsum::simsum(  data =   subset(relhaz,prev.STH==0.03), estvarname = "theta", se ="theta.se", true = 0.03, methodvar = "model", ci.limits = c("iHPD95", "uHPD95"),x = TRUE,ref = "BRGI", by =c("Schools", "Days","Slides"), control=list(level=0.95 ) )
simm.all.HPD.90.2<- rsimsum::simsum(data =   subset(relhaz,prev.STH==0.03), estvarname = "theta", se ="theta.se", true = 0.03, methodvar = "model", ci.limits = c("iHPD90", "uHPD90"),x = TRUE,ref = "BRGI", by =c("Schools", "Days","Slides"), control=list(level=0.90 ) )

```




```{r}
theme_Publication <- function(base_size=14 ) {
      library(grid)
      library(ggthemes)
      (theme_foundation(base_size=base_size )
       + theme(plot.title = element_text(face = "bold",
                                         size = rel(1), hjust = 0.5),
               text = element_text(),
               panel.background = element_rect(colour = NA),
               plot.background = element_rect(colour = NA),
               panel.border = element_rect(colour = NA),
               axis.title = element_text(face = "bold",size = rel(.8)),
               axis.title.y = element_text(angle=90,vjust =2),
               axis.title.x = element_text(vjust = -0.2),
               axis.text = element_text(), 
               axis.line = element_line(colour="darkgrey"),
               axis.ticks = element_line(colour="darkgrey"),
               panel.grid.major = element_line(colour="#f0f0f0"),
               panel.grid.minor = element_blank(),
               legend.key = element_rect(colour = NA),
               legend.position = "bottom",
               legend.direction = "horizontal",
               legend.key.size= unit(0.7, "cm"),
               legend.margin = unit(0, "cm"),
               legend.title = element_text(size=6,face="italic"),
              legend.text=element_text(size=6),
               plot.margin=unit(c(10,5,5,5),"mm"),
               strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"),
               strip.text = element_text( size = 7),
               axis.text.x = element_text(size = 5),
               axis.text.y = element_text(size = 6)
          ))
      
}



scale_fill_Publication <- function(...){
      library(scales)
      discrete_scale("fill","Publication",manual_pal(values = c("#fdb462","#7fc97f","#386cb0","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3")), ...)

}

scale_colour_Publication <- function(...){
      library(scales)
      discrete_scale("colour","Publication",manual_pal(values = c("#fdb462","#7fc97f","#386cb0","#ef3b2c","#662506","#a6cee3","#fb9a99","#984ea3")), ...)

}
```


```{r box1, fig.cap="Boxplot for model bias for each scenario and number of $days$ x $slides$. The scenarios are ordered according to the average bias of each one; True prevalence = 0.01.", fig.height=8}
library(ggplot2)
library(ggpattern)

relhaz$bias<-relhaz$theta-relhaz$prev.STH

ggplot(subset(relhaz,prev.STH==0.01), aes(x=reorder(Scenario,bias,na.rm = TRUE),y=bias, pattern = as.factor(Schools), fill=as.factor(daysXslides))) +
  geom_boxplot(position="dodge",aes(fill=as.factor(daysXslides)))+geom_hline(yintercept=0, linetype="dashed", color = "black")+ facet_wrap(~model, ncol=1, scales = "free")+
  geom_point(size=0.2,alpha = 0.3)+ labs(x="Scenarios")+
  scale_fill_manual(name = "daysXslides", values = c("#FDECCD", "#BAE4B3", "#6BADD5")) +
  geom_boxplot_pattern(position = position_dodge(preserve = "single"), pattern_angle = 45, pattern_density = 0.01, pattern_spacing = 0.025, pattern_key_scale_factor = 0.6) +
  guides(pattern = guide_legend(override.aes = list(fill = "white")), fill = guide_legend(override.aes = list(pattern = "none")))+theme(legend.position="bottom", panel.background = element_blank(), axis.line = element_line(colour = "grey"), panel.grid.major = element_line(colour = "lightgray"),panel.grid.minor = element_line(colour = "lightgray"), 
panel.grid.major.y = element_blank())+labs(pattern=expression(n[schools]))+ylab("Bias")


```


```{r box2, fig.cap="Boxplot for model bias for each scenario and number of $days \\cdot slides$. The scenarios are ordered according to the average bias of each one; True prevalence = 0.03.", fig.height=8}

relhaz.p<-subset(relhaz,prev.STH==0.03)
relhaz.p$Scenario.n<-as.numeric(relhaz.p$Scenario)
relhaz.p<-relhaz.p[order(relhaz.p$Scenario.n),]



ggplot(relhaz.p, aes(x=reorder(Scenario,bias,na.rm = TRUE),y=bias, pattern = as.factor(Schools), fill=as.factor(daysXslides))) +
  geom_boxplot(position="dodge",aes(fill=as.factor(daysXslides)))+geom_hline(yintercept=0, linetype="dashed", color = "black")+ facet_wrap(~model, ncol=1, scales = "free")+
  geom_point(size=0.2,alpha = 0.3)+ labs(x="Scenarios")+
  scale_fill_manual(name = "daysXslides", values = c("#FDECCD", "#BAE4B3", "#6BADD5")) +
  geom_boxplot_pattern(position = position_dodge(preserve = "single"), pattern_angle = 45, pattern_density = 0.01, pattern_spacing = 0.025, pattern_key_scale_factor = 0.6) +
  guides(pattern = guide_legend(override.aes = list(fill = "white")), fill = guide_legend(override.aes = list(pattern = "none")))+theme(legend.position="bottom", panel.background = element_blank(), axis.line = element_line(colour = "grey"), panel.grid.major = element_line(colour = "lightgray"),panel.grid.minor = element_line(colour = "lightgray"), 
panel.grid.major.y = element_blank())+labs(pattern=expression(n[schools]))+ylab("Bias")





```



```{r c11a, cache=F, echo=FALSE}
p.simm.all.HPD.95.1<-summary(simm.all.HPD.95.1)[["summ"]]
p.simm.all.HPD.95.1<-p.simm.all.HPD.95.1[p.simm.all.HPD.95.1$stat %in% c("bias",    "cover", "mse"  ),]
p.simm.all.HPD.95.1$stat<-ifelse(p.simm.all.HPD.95.1$stat=="cover","CP 95%",p.simm.all.HPD.95.1$stat)

p.simm.all.HPD.90.1<-summary(simm.all.HPD.90.1)[["summ"]]
p.simm.all.HPD.90.1<-p.simm.all.HPD.90.1[p.simm.all.HPD.90.1$stat=="cover",]
p.simm.all.HPD.90.1$stat<-ifelse(p.simm.all.HPD.90.1$stat=="cover","CP 90%",p.simm.all.HPD.90.1$stat)
p.simm.all.HPD.95.1<-rbind(p.simm.all.HPD.95.1,p.simm.all.HPD.90.1)

p.simm.all.HPD.95.1<-subset(p.simm.all.HPD.95.1,select=-c(lower,upper))
p.simm.all.HPD.95.1<-p.simm.all.HPD.95.1[order(p.simm.all.HPD.95.1$stat),]
p.simm.all.HPD.95.1$est<-ifelse((p.simm.all.HPD.95.1$stat=="CP 90%"|p.simm.all.HPD.95.1$stat=="CP 95%")&(grepl("MoM",p.simm.all.HPD.95.1$model)),NA,p.simm.all.HPD.95.1$est)
```


```{r result1, cache=F, echo=FALSE}
pp.1<-p.simm.all.HPD.95.1%>%tidyr::pivot_wider(names_from = model, values_from = c(est,mcse))

pp.1<-pp.1[order(pp.1$Schools,pp.1$Days,pp.1$Slides),]
pp.1$Scenarios<-rep(1:(nrow(gridd)/2),each=4)

pp.1.scene<-subset(pp.1,select=c(stat,est_BRGI,est_BRGP,`est_MoM Ind`,`est_MoM Pool`))
pp.1.perf<-subset(pp.1,select=c(stat,Schools,Days,Slides,est_BRGI,mcse_BRGI,est_BRGP,mcse_BRGP,`est_MoM Ind`,`mcse_MoM Ind`,`est_MoM Pool`,`mcse_MoM Pool`))




if(knitr::is_latex_output()) {
colnames(pp.1.scene)<-c("Measures","Estimates", "Estimates", "Estimates", "Estimates" )
colnames(pp.1.perf)<-c("Measures","$n_{schools}$","$n_{days}$","$n_{slides}$","est","mcse","est","mcse","est","mcse","est","mcse")
  kableExtra::kable(pp.1.scene, caption = "Performance measure for prevalence=0.01, for each scenario by model",booktabs = T, escape=T,  digits=5, format="latex")%>%kableExtra::kable_styling(latex_options = c("striped", "scale_down"),font_size = 9,full_width = T) %>% kableExtra::add_header_above(c("Performance" = 1, "BRGI" = 1, "BRGP" = 1, "MoM Ind" = 1, "MoM Pool" = 1))%>%
  kableExtra::pack_rows("Scenario 1", 1, 4)%>%
  kableExtra::pack_rows("Scenario 2", 5, 8)%>%
  kableExtra::pack_rows("Scenario 3", 9, 12)%>%
  kableExtra::pack_rows("Scenario 4", 13, 16)%>%
  kableExtra::pack_rows("Scenario 5", 17, 20)%>%
  kableExtra::pack_rows("Scenario 6", 21, 24)%>%
  kableExtra::pack_rows("Scenario 7", 25, 28)%>%
  kableExtra::pack_rows("Scenario 8", 29, 32)
} else if (!knitr::is_latex_output() ) {
  
  
pp.1.scene%>%flextable::flextable()%>%   autofit()%>%flextable::set_caption("Performance measure for prevalence=0.01, for each scenario by model")
}



```


 




```{r c13a1, cache=F, fig.cap=" Zip Plot Comparing Simulation Results for BRGI, and BRGP True Prevalence Value 0.01, CP=0.90." }
# HPD CI of the prevalence package
simm.all.HPD.90.1.filter<-simm.all.HPD.90.1
simm.all.HPD.90.1.filter[["summ"]]<-simm.all1[["summ"]][!grepl("MoM",simm.all1[["summ"]][["model"]]),]
a1<-autoplot(simm.all.HPD.90.1.filter, type = "zip")+theme(axis.text.x = element_text(size = 6),axis.text.y = element_text(size = 6))    
```


```{r c13a2, cache=F, fig.cap=" Zip Plot Comparing Simulation Results for BRGI, and BRGP True Prevalence Value 0.01, CP=0.95." }
# HPD CI of the prevalence package
simm.all.HPD.95.1.filter<-simm.all.HPD.95.1
simm.all.HPD.95.1.filter[["summ"]]<-simm.all1[["summ"]][!grepl("MoM",simm.all1[["summ"]][["model"]]),]
a2<-autoplot(simm.all.HPD.95.1.filter, type = "zip")+theme(axis.text.x = element_text(size = 6),axis.text.y = element_text(size = 6))    

```



```{r c11b, echo=FALSE, cache=F}
p.simm.all.HPD.95.2<-summary(simm.all.HPD.95.2)[["summ"]]
p.simm.all.HPD.95.2<-p.simm.all.HPD.95.2[p.simm.all.HPD.95.2$stat %in% c("bias",    "cover", "mse"  ),]
p.simm.all.HPD.95.2$stat<-ifelse(p.simm.all.HPD.95.2$stat=="cover","CP 95%",p.simm.all.HPD.95.2$stat)

p.simm.all.HPD.90.2<-summary(simm.all.HPD.90.2)[["summ"]]
p.simm.all.HPD.90.2<-p.simm.all.HPD.90.2[p.simm.all.HPD.90.2$stat=="cover",]
p.simm.all.HPD.90.2$stat<-ifelse(p.simm.all.HPD.90.2$stat=="cover","CP 90%",p.simm.all.HPD.90.2$stat)
p.simm.all.HPD.95.2<-rbind(p.simm.all.HPD.95.2,p.simm.all.HPD.90.2)

p.simm.all.HPD.95.2<-subset(p.simm.all.HPD.95.2,select=-c(lower,upper))
p.simm.all.HPD.95.2<-p.simm.all.HPD.95.2[order(p.simm.all.HPD.95.2$stat),]
p.simm.all.HPD.95.2$est<-ifelse((p.simm.all.HPD.95.2$stat=="CP 90%"|p.simm.all.HPD.95.2$stat=="CP 95%")&(grepl("MoM",p.simm.all.HPD.95.2$model)),NA,p.simm.all.HPD.95.2$est)
```





```{r result2, cache=F, echo=FALSE}
pp.2<-p.simm.all.HPD.95.2%>%tidyr::pivot_wider(names_from = model, values_from = c(est,mcse))
pp.2<-pp.2[order(pp.2$Schools,pp.2$Days,pp.2$Slides),]
pp.2$Scenarios<-rep((1+8):(nrow(gridd)/2+8),each=4)

pp.2.scene<-subset(pp.2,select=c(stat,est_BRGI,est_BRGP,`est_MoM Ind`,`est_MoM Pool`))
pp.2.perf<-subset(pp.2,select=c(stat,Schools,Days,Slides,est_BRGI,mcse_BRGI,est_BRGP,mcse_BRGP,`est_MoM Ind`,`mcse_MoM Ind`,`est_MoM Pool`,`mcse_MoM Pool`))


if(knitr::is_latex_output()) {
colnames(pp.2.scene)<-c("Measures","Estimates", "Estimates", "Estimates", "Estimates" )
colnames(pp.2.perf)<-c("Measures","$n_{schools}$","$n_{days}$","$n_{slides}$","est","mcse","est","mcse","est","mcse","est","mcse")
  
pp.2.scene%>% kableExtra::kable(caption = "Performance measure for prevalence=0.03, for each scenario by model",escape=T,  booktabs = T,  format="latex", digits=5 )%>%kableExtra::kable_styling(font_size = 9,latex_options = c("striped", "scale_down"),full_width = T)%>%kableExtra::add_header_above(c("Performance" = 1, "BRGI" = 1, "BRGP" = 1, "MoM Ind" = 1, "MoM Pool" = 1))%>%
  kableExtra::pack_rows("Scenario 9", 1, 4)%>%
  kableExtra::pack_rows("Scenario 10", 5, 8)%>%
  kableExtra::pack_rows("Scenario 11", 9, 12)%>%
  kableExtra::pack_rows("Scenario 12", 13, 16)%>%
  kableExtra::pack_rows("Scenario 13", 17, 20)%>%
  kableExtra::pack_rows("Scenario 14", 21, 24)%>%
  kableExtra::pack_rows("Scenario 15", 25, 28)%>%
  kableExtra::pack_rows("Scenario 16", 29,32)
} else if (!knitr::is_latex_output() ) {
pp.2.scene%>% flextable::flextable()%>%autofit()%>%flextable::set_caption("Performance measure for prevalence=0.03, for each scenario by model")
}
 
 
```





 



```{r}
# HPD CI of the prevalence package
simm.all.HPD.90.2.filter<-simm.all.HPD.90.2
simm.all.HPD.90.2.filter[["summ"]]<-simm.all2[["summ"]][!grepl("MoM",simm.all2[["summ"]][["model"]]),]
b1<-autoplot(simm.all.HPD.90.2.filter, type = "zip")+theme(axis.text.x = element_text(size = 6),axis.text.y = element_text(size = 6))    
```


```{r, fig.cap=" Zip Plot Comparing Simulation Results for BRGI, and BRGP True Prevalence Value 0.03, CP=0.95.", eval=TRUE, include=T}
# HPD CI of the prevalence package
simm.all.HPD.95.2.filter<-simm.all.HPD.95.2
simm.all.HPD.95.2.filter[["summ"]]<-simm.all2[["summ"]][!grepl("MoM",simm.all2[["summ"]][["model"]]),]
b2<-autoplot(simm.all.HPD.95.2.filter, type = "zip")+theme(axis.text.x = element_text(size = 6),axis.text.y = element_text(size = 6))    
```
 
 
 


 

```{r c20}

relhaz$Treat.class <-
  ifelse(relhaz$prev.STH == 0.03 & relhaz$theta < 0.02,"UT",
         ifelse(relhaz$prev.STH == 0.01 & relhaz$theta >= 0.02 ,"OT",
                ifelse(relhaz$theta < 0.02  & relhaz$prev.STH == 0.01,"CT",
                       ifelse(relhaz$theta >= 0.02  & relhaz$prev.STH == 0.03,"CT",NA))))


```






```{r,eval=F,include=F}
\begin{table}[!htb]
    \begin{minipage}{.52\linewidth}
      \centering

```


\begin{table}[H]
\centering

```{r c21}

                                                                                                  ctg1<-(table(relhaz$Treat.class, relhaz$model)/(nrow(relhaz)/4))%>%as.data.frame()
ctg1.w<-ctg1%>%tidyr::pivot_wider(names_from = Var2, values_from = c(Freq))
library(scales)
ctg1.w$BRGI<-scales::percent(round(ctg1.w$BRGI, digits=4))
ctg1.w$BRGP<-scales::percent(round(ctg1.w$BRGP, digits=4))
ctg1.w$`MoM Ind`<-scales::percent(round(ctg1.w$`MoM Ind`, digits=4))
ctg1.w$`MoM Pool`<-scales::percent(round(ctg1.w$`MoM Pool`, digits=4))


if(knitr::is_latex_output()) {
colnames(ctg1.w)<-c("",colnames(ctg1.w)[-1])
ctg1.w%>%kableExtra::kable(  escape=T,booktabs = T ,caption = "Cross tabulation between Percentage of Corrected Treated (CT), Overtreated (OT), \n Undertreated (UT) across the estimator methods", digits=2, align = "lrrrr")%>% kableExtra::kable_styling(font_size = 9, latex_options = c("striped","HOLD_position"))
} else if (!knitr::is_latex_output() ) {

ctg1.w%>%as.data.frame()%>% flextable::flextable()  %>%autofit()%>%flextable::set_caption("Number of Corrected Treated (CT), Overtreated (OT), \n Undertreated (UT) across the estimator methods")
}

```


 

```{r c22}
 
ctg2<-xtabs(~ Treat.class+  model+ Schools, data=relhaz)%>%as.data.frame()

ctg2.w<-ctg2%>%tidyr::pivot_wider(names_from = model, values_from = c(Freq))
#ctg2.w$Total<-colSums(ctg2.w[,c(3:6)])

ctg2.w$BRGI<-scales::percent(round(ctg2.w$BRGI/1600, digits=4))
ctg2.w$BRGP<-scales::percent(round(ctg2.w$BRGP/1600, digits=4))
ctg2.w$`MoM Ind`<-scales::percent(round(ctg2.w$`MoM Ind`/1600, digits=4))
ctg2.w$`MoM Pool`<-scales::percent(round(ctg2.w$`MoM Pool`/1600, digits=4))


if(knitr::is_latex_output()) {
colnames(ctg2.w)<-c("",colnames(ctg2.w)[-1])
ctg2.w%>%kableExtra::kable(  escape=T,booktabs = T ,caption = "Cross tabulation between Percentage of Corrected Treated (CT), Overtreated (OT), \n Undertreated (UT) across the estimator methods", align = "llrrrr")%>% kableExtra::kable_styling(font_size = 9, latex_options = c("striped","HOLD_position"))
} else if (!knitr::is_latex_output() ) {
 
ctg2.w%>% flextable::flextable()%>%autofit()%>%flextable::set_caption("Number of Corrected Treated (CT), Overtreated (OT), \n Undertreated (UT) across the estimator methods")
}

```
 

```{r,eval=F,include=F}

\end{minipage}%
  \begin{minipage}{.52\linewidth}
    \centering
```

 
```{r c23}
ctg3<-xtabs(~ Treat.class+  model+ daysXslides, data=relhaz)%>%as.data.frame()
ctg3.w<-ctg3%>%tidyr::pivot_wider(names_from = model, values_from = c(Freq))
ctg3.w$BRGI<-scales::percent(round(ctg3.w$BRGI/1600, digits=4))
ctg3.w$BRGP<-scales::percent(round(ctg3.w$BRGP/1600, digits=4))
ctg3.w$`MoM Ind`<-scales::percent(round(ctg3.w$`MoM Ind`/1600, digits=4))
ctg3.w$`MoM Pool`<-scales::percent(round(ctg3.w$`MoM Pool`/1600, digits=4))



if(knitr::is_latex_output()) {
colnames(ctg3.w)<-c("",colnames(ctg3.w)[-1])
ctg3.w<-ctg3.w[,-2] 
ctg3.w%>%kableExtra::kable(escape=T, longtable = TRUE, booktabs = T,  caption = "Cross tabulation between a) Percentage of Corrected Treated (CT), Overtreated (OT), \n Undertreated (UT) across estimator methods and number of $days$*number of $slides$", align = "lrrrr")%>%column_spec(1, width="4cm")%>% kableExtra::kable_styling(font_size = 9,  latex_options = c("striped","HOLD_position"))%>%
kableExtra::pack_rows("daysXslides=1", 1, 3)%>%
  kableExtra::pack_rows("daysXslides=2", 4, 6)%>%
  kableExtra::pack_rows("daysXslides=4", 7, 9)  %>%   kableExtra::column_spec(3, width = "2cm")  %>%   kableExtra::column_spec(4, width = "2cm")    
} else if (!knitr::is_latex_output() ) {
ctg3.w%>% flextable::flextable()%>%autofit()%>%flextable::set_caption("Cross tabulation between a) Percentage of Corrected Treated (CT), Overtreated (OT), \n Undertreated (UT) across estimator methods and number of $days$*number of $slides$")
}


```

```{r,eval=F,include=F}

   \end{minipage} 
\end{table}
```

\end{table}




```{r, cache=F}
#rm(list=ls())
library(dplyr)
setwd("C:/Users/32498/Documents/Master EPI/SEM6/STH_THESIS_2023/ThesisSTH/DATA_LEVECKE/Leta et al., 2018/")
#setwd("./DATA_LEVECKE/Leta et al., 2018/")
ind <- read.csv("GT_Ind_19JAN2016.csv")
pool <- read.csv("GT_Pool_19JAN2016.csv")
ind <- subset(ind,select=-c(Other,Reading.time..MIN.,Reading.time..SEC.,X,X.1,X.2,X.3))
pool <-subset(pool,select=-c(other,Reading.time..MIN.,Reading.time..SEC.,X,X.1,X.2,X.3,X.4,X.5)) 



## Organizing Data
library(plyr)

ind$n <- 1

# EPG
ind$EPG_AL <- ind$Eggs.of.Ascaris*24
ind$EPG_HK <- ind$Eggs.of.Hookworm*24
ind$EPG_TT <- ind$Eggs.of.Trichuris*24
ind$EPG_SM <- ind$Eggs.of.Schistosoma*24

pool$EPG_AL_P <- pool$Eggs.of.Ascaris*24
pool$EPG_HK_P <- pool$Eggs.of.Hookworm*24
pool$EPG_TT_P <- pool$Eggs.of.Trichuris*24
pool$EPG_SM_P <- pool$Eggs.of.Schistosoma*24

# positive/negative Test results
ind$P_AL <- ifelse(ind$Eggs.of.Ascaris==0,0,1)
ind$P_HK <- ifelse(ind$Eggs.of.Hookworm==0,0,1)
ind$P_TT <- ifelse(ind$Eggs.of.Trichuris==0,0,1)
ind$P_SM <- ifelse(ind$Eggs.of.Schistosoma==0,0,1)
ind$mix <- ind$P_AL + ind$P_HK + ind$P_TT + ind$P_SM
ind$sth <- ind$P_AL + ind$P_HK + ind$P_TT
ind$P_sth <- ifelse(ind$sth==0,0,1)
ind$P_ntd <- ifelse(ind$mix==0,0,1)

pool$P_AL_P <- ifelse(pool$Eggs.of.Ascaris==0,0,1)
pool$P_HK_P <- ifelse(pool$Eggs.of.Hookworm==0,0,1)
pool$P_TT_P <- ifelse(pool$Eggs.of.Trichuris==0,0,1)
pool$P_SM_P <- ifelse(pool$Eggs.of.Schistosoma==0,0,1)

## intensity of infection, categories based on the # STH EPG and STH type
ind$Int_AL <- ifelse(ind$EPG_AL == 0, 0, ifelse(ind$EPG_AL < 5000, 1, ifelse(ind$EPG_AL>49999,3,2)))
ind$Int_TT <- ifelse(ind$EPG_TT == 0, 0, ifelse(ind$EPG_TT < 1000, 1, ifelse(ind$EPG_TT>9999,3,2)))
ind$Int_HK<- ifelse(ind$EPG_HK == 0, 0, ifelse(ind$EPG_HK < 2000, 1, ifelse(ind$EPG_TT>3999,3,2)))
ind$Int_SM<- ifelse(ind$EPG_SM == 0, 0, ifelse(ind$EPG_SM < 100, 1, ifelse(ind$EPG_TT>399,3,2)))


#For each subset of a data frame, apply function then combine results into a data frame. 
# For every region (Woreda code) and school, we are calculating observed STH prevalence and average STH EPG
sum <-
  plyr::ddply(
    .data = ind,
    .variables = .(Woreda.code, School.Code),
    .fun = plyr::summarize,
    n = sum(n),
    schi_p = round(100 * mean(P_SM), 1),
    asc_p = round(100 * mean(P_AL), 1),
    hoo_p = round(100 * mean(P_HK), 1),
    tri_p = round(100 * mean(P_TT), 1),
    schi = round(mean(EPG_SM), 1),
    asc = round(mean(EPG_AL), 1),
    hoo = round(mean(EPG_HK), 1),
    tri = round(mean(EPG_TT), 1)
  )

sum$ntd <- sum$schi_p + sum$asc_p + sum$hoo_p + sum$tri_p
ntd <- subset(sum, sum$ntd==0)
```



```{r}
## intensity of infection
ind$Int_AL <- ifelse(ind$EPG_AL == 0, 0, ifelse(ind$EPG_AL < 5000, 1, ifelse(ind$EPG_AL>49999,3,2)))
ind$Int_TT <- ifelse(ind$EPG_TT == 0, 0, ifelse(ind$EPG_TT < 1000, 1, ifelse(ind$EPG_TT>9999,3,2)))
ind$Int_HK<- ifelse(ind$EPG_HK == 0, 0, ifelse(ind$EPG_HK < 2000, 1, ifelse(ind$EPG_TT>3999,3,2)))


Inf.int<-rbind(
c("\\textit{Ascaris}",table(ind$Int_AL)),
c("\\textit{Hookworm}",table(ind$Int_HK)),
c("\\textit{Trichuris}",table(ind$Int_TT)))
colnames(Inf.int)<-c("STHs Type","Light","Moderate","Heavy")

Inf.int<-as.data.frame(Inf.int)
col.sss<-c("Light","Moderate","Heavy")
Inf.int<-Inf.int%>%mutate_at(col.sss, as.numeric)


Inf.int.2<-rbind(
c("Ascaris","EPG<5000","5000<EPG<49999","EPG>49999"),
c("Hookworm","EPG<2000","2000<EPG<3999","EPG>3999"),
c("Trichuris","EPG<1000","1000<EPG<9999","EPG>9999"))
colnames(Inf.int.2)<-c("STHs Type","Low","Moderate","High")



```




```{r IIWHO}


Inf.int.2<-Inf.int.2[-4,]
 
Inf.int.2[1,1]<-char("\\textit{Ascaris}")
Inf.int.2[2,1]<-char("\\textit{Hookworms}")
Inf.int.2[3,1]<-char("\\textit{Trichuris}")


if(knitr::is_latex_output()) {Inf.int.2%>%kableExtra::kable( booktabs = T,  caption = "Classification criteria of STHs Infection intensity",escape = FALSE )%>% kableExtra::kable_styling(  latex_options = c("striped","HOLD_position"))
} else if (!knitr::is_latex_output() ) {
Inf.int.2%>%as.data.frame%>% flextable::flextable()%>%autofit()%>%flextable::set_caption("Classification criteria of STHs Infection intensity")
}


```


```{r IIEtiopia}



if(knitr::is_latex_output()) {
Inf.int%>%kableExtra::kable( booktabs = T,  caption = "Classification of STH infection intensity for all subjects in Ethiopia survey",escape = FALSE)%>% kableExtra::kable_styling(  latex_options = c("striped","HOLD_position"))%>%
  kableExtra::add_footnote(c(" "),  notation="none") 
} else if (!knitr::is_latex_output() ) {
Inf.int%>%as.data.frame%>% flextable::flextable()%>%autofit()%>%flextable::set_caption("Classification of STHs Infection intensity for all subjects in Ethiopia survey")
}




Inf.int$Total<-Inf.int$Light+Inf.int$Moderate+Inf.int$Heavy
Inf.int$P.Light<-100*(Inf.int$Light/Inf.int$Total)
Inf.int$P.Moderate<-100*(Inf.int$Moderate/Inf.int$Total)
Inf.int$P.Heavy<-100*(Inf.int$Heavy/Inf.int$Total)
```
  
    
    
 

```{r, cache=F}
### Merging individual and pooled samples
### 
# For every region (Woreda code) and school AND POOL.ID, we are calculating observed STH prevalence and average STH EPG
sum2 <- ddply(ind, .(Woreda.code,School.Code,Pool.ID), plyr::summarize,n = sum(n),schi = mean(EPG_SM),asc= mean(EPG_AL),hoo= mean(EPG_HK),tri= mean(EPG_TT))
TOT <- merge(sum2,pool,by=c("Woreda.code","School.Code",'Pool.ID'), all.Y = T)
#TOT[1:10,]
TOT$N <- 1


library(Hmisc)
var.labels = c(Woreda.code="Woreda code",
               School.Code="School Code",
               Pool.ID="Pool ID",
               n="n",
               schi="schi",
               asc="asc",
               hoo="hoo",
               tri="tri",
               min="Time min",
               sec="Time sec",
               Woreda.name="Woreda name",
               School.Name="School Name",
               Eggs.of.Schistosoma="Eggs of Schistosoma",
               Eggs.of.Ascaris="Eggs of Ascaris",
               Eggs.of.Hookworm="Eggs of Hookworm",
               Eggs.of.Trichuris="Eggs of Trichuris",
               other="other",
               EPG_AL_P="EPG_AL_P",
               EPG_HK_P="EPG_HK_P",
               EPG_TT_P="EPG_TT_P",
               EPG_SM_P="EPG_SM_P",
               P_AL_P="P_AL_P",
               P_HK_P="P_HK_P",
               P_TT_P="P_TT_P",
               P_SM_P="P_SM_P",
               N="N")

label(TOT) = as.list(var.labels[match(names(TOT), names(var.labels))])

library(prevalence)
```


```{r}
library("plotrix")

#INDividual 
MoMI <- function(EPG.n=NA, School.n=NA,day.n=1,slide.n=1) {
True.Pre.MoM <- 1 - dnbinom(0,
            mu = tapply(EPG.n, School.n, mean),
            size = tapply(EPG.n, School.n, mean) / ((
              tapply(EPG.n, School.n, var) / tapply(EPG.n, School.n, mean)) - 24 /(day.n*slide.n) - 1))
         Perc.zero <- sum(True.Pre.MoM == 'NaN')/length(True.Pre.MoM)
         True.Pre.MoM <- ifelse(True.Pre.MoM == 'NaN', 0, True.Pre.MoM)
        
        SE.True.Pre.MoM <- std.error(as.vector(True.Pre.MoM))
        SD.True.Pre.MoM <- sd(as.vector(True.Pre.MoM))
        True.Pre.MoM <- mean(True.Pre.MoM)
        salida<-data.frame(Prevalence=True.Pre.MoM,SE.Prevalence=SE.True.Pre.MoM,SD.True.Pre.MoM,Perc.zero=Perc.zero)
        return(salida)
}

        

#POOLED        
MoMP <- function(EPG.n=NA, School.n=NA,day.n=1,slide.n=1,pool.size=10) {
True.Pre.MoM <-1 - dnbinom(0,
            mu = tapply(EPG.n, School.n, mean),
            size = tapply(EPG.n, School.n, mean) / ((
              pool.size*tapply(EPG.n, School.n, var) / tapply(EPG.n, School.n, mean)) - 24 /(day.n*slide.n) - 1))
         Perc.zero <- sum(True.Pre.MoM == 'NaN')/length(True.Pre.MoM)
        True.Pre.MoM <- ifelse(True.Pre.MoM == 'NaN', 0, True.Pre.MoM)
        SE.True.Pre.MoM <- std.error(as.vector(True.Pre.MoM))
        SD.True.Pre.MoM <- sd(as.vector(True.Pre.MoM))
        True.Pre.MoM <- mean(True.Pre.MoM)
        salida<-data.frame(Prevalence=True.Pre.MoM,SE.Prevalence=SE.True.Pre.MoM,SD.True.Pre.MoM,Perc.zero=Perc.zero)
        return(salida)
 }
```

```{r, echo=FALSE, cache=F}
library(dplyr); library(pander)

#IND PREV

Prev.P_AL<-truePrev(x = sum(ind$P_AL), n = nrow(ind),SE = ~dunif(0.40, 1.00), SP = ~dunif(0.9, 1.00))%>%summary()%>%as.data.frame
Prev.P_HK<-truePrev(x = sum(ind$P_HK), n = nrow(ind),SE = ~dunif(0.40, 1.00), SP = ~dunif(0.9, 1.00))%>%summary()%>%as.data.frame
Prev.P_TT<-truePrev(x = sum(ind$P_TT), n = nrow(ind),SE = ~dunif(0.40, 1.00), SP = ~dunif(0.9, 1.00))%>%summary()%>%as.data.frame
Prev.P_SM<-truePrev(x = sum(ind$P_SM), n = nrow(ind),SE = ~dunif(0.40, 1.00), SP = ~dunif(0.9, 1.00))%>%summary()%>%as.data.frame


Prev.P_AL<-Prev.P_AL[3,]
Prev.P_HK<-Prev.P_HK[3,]
Prev.P_TT<-Prev.P_TT[3,]
Prev.P_SM<-Prev.P_SM[3,]

Prev.P_AL<-subset(Prev.P_AL,select = c(TP.mean,TP.sd,TP.2.5.,TP.97.5.,SE.mean,SE.2.5.,SE.97.5.,SP.mean,SP.2.5.,SP.97.5.))
Prev.P_HK<-subset(Prev.P_HK,select = c(TP.mean,TP.sd,TP.2.5.,TP.97.5.,SE.mean,SE.2.5.,SE.97.5.,SP.mean,SP.2.5.,SP.97.5.))
Prev.P_TT<-subset(Prev.P_TT,select = c(TP.mean,TP.sd,TP.2.5.,TP.97.5.,SE.mean,SE.2.5.,SE.97.5.,SP.mean,SP.2.5.,SP.97.5.))
Prev.P_SM<-subset(Prev.P_SM,select = c(TP.mean,TP.sd,TP.2.5.,TP.97.5.,SE.mean,SE.2.5.,SE.97.5.,SP.mean,SP.2.5.,SP.97.5.))



#POOLED PREV
Prev.P_AL_P<-prevalence::truePrevPools(x=as.integer(TOT$P_AL_P), n=as.integer(TOT$n),SE = ~dunif(0.40, 1.00), SP = ~dunif(0.9, 1.00),prior = c(1, 1),nchains = 2, burnin = 10000, update = 10000,verbose = FALSE)%>%summary()%>%as.data.frame
Prev.P_HK_P<-prevalence::truePrevPools(x=as.integer(TOT$P_HK_P), n=as.integer(TOT$n),SE = ~dunif(0.40, 1.00), SP = ~dunif(0.9, 1.00), prior = c(1, 1),nchains = 2, burnin = 10000, update = 10000,verbose = FALSE)%>%summary()%>%as.data.frame
Prev.P_TT_P<-prevalence::truePrevPools(x=as.integer(TOT$P_TT_P), n=as.integer(TOT$n),SE = ~dunif(0.40, 1.00), SP = ~dunif(0.9, 1.00), prior = c(1, 1),nchains = 2, burnin = 10000, update = 10000,verbose = FALSE)%>%summary()%>%as.data.frame
Prev.P_SM_P<-prevalence::truePrevPools(x=as.integer(TOT$P_SM_P), n=as.integer(TOT$n),SE = ~dunif(0.40, 1.00), SP = ~dunif(0.9, 1.00), prior = c(1, 1),nchains = 2, burnin = 10000, update = 10000,verbose = FALSE)%>%summary()%>%as.data.frame


Prev.P_AL_P<-Prev.P_AL_P[3,]
Prev.P_HK_P<-Prev.P_HK_P[3,]
Prev.P_TT_P<-Prev.P_TT_P[3,]
Prev.P_SM_P<-Prev.P_SM_P[3,]

Prev.P_AL_P<-subset(Prev.P_AL_P,select=c(TP.mean,TP.sd,TP.2.5.,TP.97.5.,SE.mean,SE.2.5.,SE.97.5.,SP.mean,SP.2.5.,SP.97.5.))
Prev.P_HK_P<-subset(Prev.P_HK_P,select=c(TP.mean,TP.sd,TP.2.5.,TP.97.5.,SE.mean,SE.2.5.,SE.97.5.,SP.mean,SP.2.5.,SP.97.5.))
Prev.P_TT_P<-subset(Prev.P_TT_P,select=c(TP.mean,TP.sd,TP.2.5.,TP.97.5.,SE.mean,SE.2.5.,SE.97.5.,SP.mean,SP.2.5.,SP.97.5.))
Prev.P_SM_P<-subset(Prev.P_SM_P,select=c(TP.mean,TP.sd,TP.2.5.,TP.97.5.,SE.mean,SE.2.5.,SE.97.5.,SP.mean,SP.2.5.,SP.97.5.))



#NAIVE PREVALENCE
Prev.OP_AL<-propCI(x = sum(ind$P_AL), n = nrow(ind),method = "exact", level = 0.95, sortby = "level")
Prev.OP_HK<-propCI(x = sum(ind$P_HK), n = nrow(ind),method = "exact", level = 0.95, sortby = "level")
Prev.OP_TT<-propCI(x = sum(ind$P_TT), n = nrow(ind),method = "exact", level = 0.95, sortby = "level")
Prev.OP_SM<-propCI(x = sum(ind$P_SM), n = nrow(ind),method = "exact", level = 0.95, sortby = "level")
OP.exact<-rbind(c(Prev.OP_AL$p, NA,Prev.OP_AL$lower,Prev.OP_AL$upper,NA,NA,NA,NA,NA,NA,"Ascaris","GS Exact"),
c(Prev.OP_HK$p, NA,Prev.OP_HK$lower,Prev.OP_HK$upper,NA,NA,NA,NA,NA,NA,"Hookworm","GS Exact"),
c(Prev.OP_TT$p, NA,Prev.OP_TT$lower,Prev.OP_TT$upper,NA,NA,NA,NA,NA,NA,"Trichuris","GS Exact"),
c(Prev.OP_SM$p, NA,Prev.OP_SM$lower,Prev.OP_SM$upper,NA,NA,NA,NA,NA,NA,"Schistosoma","GS Exact"))
OP.exact<-as.data.frame(OP.exact)


#MERGING
Prev.Ind<-rbind(Prev.P_AL,Prev.P_HK,Prev.P_TT,Prev.P_SM)
Prev.Ind$STHs.Type<-c("Ascaris","Hookworm","Trichuris","Schistosoma")
Prev.Ind$model<-c("BRGI","BRGI","BRGI","BRGI")
Prev.Pool<-rbind(Prev.P_AL_P,Prev.P_HK_P,Prev.P_TT_P,Prev.P_SM_P)
Prev.Pool$STHs.Type<-c("Ascaris","Hookworm","Trichuris","Schistosoma")
Prev.Pool$model<-c("BRGP","BRGP","BRGP","BRGP")
Prev.IP<-rbind(Prev.Ind,Prev.Pool)
row.names(Prev.IP)<-NULL
colnames(OP.exact)<-colnames(Prev.IP)
Prev.IP<-rbind(Prev.IP,OP.exact)


MOMI<-rbind(
c(MoMI(EPG.n=ind$EPG_AL, School.n=as.factor(ind$School.Name),day.n=1,slide.n=1)[1], 
  MoMI(EPG.n=ind$EPG_AL, School.n=as.factor(ind$School.Name),day.n=1,slide.n=1)[3],NA,NA,NA,NA,NA,NA,NA,NA,"Ascaris","MoM Ind"),
c(MoMI(EPG.n=ind$EPG_HK, School.n=as.factor(ind$School.Name),day.n=1,slide.n=1)[1],
  MoMI(EPG.n=ind$EPG_HK, School.n=as.factor(ind$School.Name),day.n=1,slide.n=1)[3],NA,NA,NA,NA,NA,NA,NA,NA,"Hookworm","MoM Ind"),
c(MoMI(EPG.n=ind$EPG_TT, School.n=as.factor(ind$School.Name),day.n=1,slide.n=1)[1],
  MoMI(EPG.n=ind$EPG_TT, School.n=as.factor(ind$School.Name),day.n=1,slide.n=1)[3],NA,NA,NA,NA,NA,NA,NA,NA,"Trichuris","MoM Ind"),
c(MoMI(EPG.n=ind$EPG_SM, School.n=as.factor(ind$School.Name),day.n=1,slide.n=1)[1],
  MoMI(EPG.n=ind$EPG_SM, School.n=as.factor(ind$School.Name),day.n=1,slide.n=1)[3],NA,NA,NA,NA,NA,NA,NA,NA,"Schistosoma","MoM Ind"))
MOMI<-as.data.frame(MOMI)
colnames(MOMI)<-colnames(Prev.IP)


MOMP<-rbind(
c(MoMP(EPG.n=TOT$EPG_AL_P, School.n=TOT$School.Code,day.n=1,slide.n=1,pool.size=10)[1],
  MoMP(EPG.n=TOT$EPG_AL_P, School.n=TOT$School.Code,day.n=1,slide.n=1,pool.size=10)[3],NA,NA,NA,NA,NA,NA,NA,NA,"Ascaris","MoM Pool"),
c(MoMP(EPG.n=TOT$EPG_HK_P, School.n=TOT$School.Code,day.n=1,slide.n=1,pool.size=10)[1],
  MoMP(EPG.n=TOT$EPG_HK_P, School.n=TOT$School.Code,day.n=1,slide.n=1,pool.size=10)[3],NA,NA,NA,NA,NA,NA,NA,NA,"Hookworm","MoM Pool"),
c(MoMP(EPG.n=TOT$EPG_TT_P, School.n=TOT$School.Code,day.n=1,slide.n=1,pool.size=10)[1],
  MoMP(EPG.n=TOT$EPG_TT_P, School.n=TOT$School.Code,day.n=1,slide.n=1,pool.size=10)[3],NA,NA,NA,NA,NA,NA,NA,NA,"Trichuris","MoM Pool"),
c(MoMP(EPG.n=TOT$EPG_SM_P, School.n=TOT$School.Code,day.n=1,slide.n=1,pool.size=10)[1],
  MoMP(EPG.n=TOT$EPG_SM_P, School.n=TOT$School.Code,day.n=1,slide.n=1,pool.size=10)[3],NA,NA,NA,NA,NA,NA,NA,NA,"Schistosoma","MoM Pool"))
MOMP<-as.data.frame(MOMP)
colnames(MOMP)<-colnames(Prev.IP)

Prev.IP<-rbind(Prev.IP,MOMI,MOMP)



#Label
var.labels2 = c(TP.mean="estimate",
TP.sd="sd",
TP.2.5.="LIC",
TP.97.5.="UIC",
SE.mean="Est",
SE.2.5.="LIC",
SE.97.5.="UIC",
SP.mean="Est",
SP.2.5.="LIC",
SP.97.5.="UIC",
STHs.Type="STH type",
model="Model")
label(Prev.IP) = as.list( var.labels2[match(names(Prev.IP), names(var.labels2))] )

```



```{r EtiPrev1, echo=FALSE, cache=F}
Prev.IP$orden<-ifelse(Prev.IP$STHs.Type=="Ascaris",1,ifelse(Prev.IP$STHs.Type=="Hookworm",2,ifelse(Prev.IP$STHs.Type=="Trichuris",3,ifelse(Prev.IP$STHs.Type=="Schistosoma",4,NA))))
options(digits=3)
library(dplyr)
Prev.IP<-Prev.IP[order(Prev.IP$orden),]

col.sel<-c('TP.mean','TP.sd','TP.2.5.','TP.97.5.','SE.mean','SE.2.5.','SE.97.5.','SP.mean','SP.2.5.','SP.97.5.')
Prev.IP <- Prev.IP%>% mutate_at(col.sel, as.numeric)%>% mutate(across(col.sel, round, 3))

Prev.IP.text <-
  as.data.frame(cbind(
    Prev.IP$model,
    Prev.IP$STHs.Type,
    paste0(
      round(Prev.IP$TP.mean,digits =3),"(",
      round(Prev.IP$TP.sd,digits =3),") [",
      round(Prev.IP$TP.2.5.,digits =3),",",
      round(Prev.IP$TP.97.5.,digits =3),"]"
    ),
    paste0(
      round(Prev.IP$SE.mean,digits = 3),"[",
      round(Prev.IP$SE.2.5.,digits = 3),",",
      round(Prev.IP$SE.97.5.,digits = 3),"]"
    ),
    paste0(
      round(Prev.IP$SP.mean,digits = 3),"[",
      round(Prev.IP$SP.2.5.,digits = 3),",",
      round(Prev.IP$SP.97.5.,digits = 3),"]"
    )
  ))

#substr(Prev.IP.text$V3)
Prev.IP.text$V3<-gsub("NA", "   -   ", Prev.IP.text$V3)
Prev.IP.text$V4<-gsub("NA", "   -   ", Prev.IP.text$V4)
Prev.IP.text$V5<-gsub("NA", "   -   ", Prev.IP.text$V5)

Prev.IP<-subset(Prev.IP,select = -c(orden))

label(Prev.IP) = as.list( var.labels2[match(names(Prev.IP), names(var.labels2))] )

Prev.IP<-subset(Prev.IP,select = -c(STHs.Type))
Prev.IP<-Prev.IP[,c(11,1:10)]

#str(Prev.IP)
#library(dplyr)
Prev.IP.5<-Prev.IP[,c(1:5)]



Prev.IP.5$graph<-' '


# Deleting the Schistosoma: [1:15,]

if(knitr::is_latex_output()) {Prev.IP.5[1:15,]%>% kableExtra::kable( escape=T, booktabs = T, row.names = FALSE, col.names= label(Prev.IP.5),digits=4, caption = "STHs prevalence for Ethiopia survey, according  to  BRGI, BRGP, MoMI, MoMP, and Naive GS exact method estimators")%>%
  kableExtra::kable_styling(latex_options = c("striped","HOLD_position"),font_size = 9,full_width = F)%>% 
  kableExtra::add_header_above(c( "Estimator" = 1,"Prevalence" = 5))%>%
  kableExtra::pack_rows("Ascaris *",1,5,italic=T,hline_after = T)%>%
  kableExtra::pack_rows("hookworms",6,10,italic=T,hline_after = T)%>%
  kableExtra::pack_rows("Trichuris", 11, 15,italic=T,hline_after = T)%>%
  column_spec(6,width = "4em", image = spec_pointrange(x = Prev.IP.5$TP.mean,xmin = Prev.IP.5$TP.2.5.,xmax = Prev.IP.5$TP.97.5., threeparttable = TRUE,vline = c(.02), lim=c(0,0.17)))%>% 
  kableExtra::add_footnote(c("Est: Estimate, sd: standard deviation, LIC: Lower Interval Credible, \n UIC: Upper Interval Credible, GS: Gold Standard. The vertical line for \n  the graphical represation column of prevalence estimate is set in 2% threshold"), notation="none")%>%
add_footnote("The MoM Ind estimates of Ascaris prevalence are not presented to avoid \n missing the appropriate scale for the rest of the estimates.",notation = "symbol")

} else if (!knitr::is_latex_output() ) {
Prev.IP.5%>% flextable::flextable()%>%autofit()%>%flextable::set_caption("STHs prevalence for Ethiopia survey, according  to BRGI, BRGP, MoMI, MoMP, and Naive GS exact method estimators")
}




options(digits=7)



```

\begin{table}[H]
\centering
```{r EtiPrev2}
options(digits=4)

# Deleting the Schistosoma: [1:6,]

if(knitr::is_latex_output()) {Prev.IP[(Prev.IP$model=='BRGI'| Prev.IP$model=='BRGP'),c(1,6:11)][1:6,]%>% kableExtra::kable( escape=T,booktabs = T, row.names = FALSE, col.names= label(Prev.IP[(Prev.IP$model=='BRGI'| Prev.IP$model=='BRGP'),c(1,6:11)]),digits=4, caption = "KK Sensitivity, KK Specificity estimates for Ethiopia survey, according  to BRGI, BRGP method estimators")%>%kableExtra::kable_styling(position = "center", latex_options = c("striped","HOLD_position"),font_size = 9)%>% 
  kableExtra::add_header_above(c( "Estimator" = 1,"Sensitivity" = 3, "Specificity" = 3))%>%
  kableExtra::pack_rows("Ascaris", 1, 2)%>%
  kableExtra::pack_rows("Hookworm", 3, 4)%>%
  kableExtra::pack_rows("Trichuris", 5, 6)%>%
   kableExtra::add_footnote(c("Est: Estimate, sd: standard deviation, LIC: Lower Interval Credible, \n UIC: Upper Interval Credible"),   notation="none") 
} else if (!knitr::is_latex_output() ) {
Prev.IP[(Prev.IP$model=='BRGI'| Prev.IP$model=='BRGP'),c(1,6:11)]%>% flextable::flextable()%>%autofit()%>%flextable::set_caption("KK Sensitivity, KK Specificity estimates for Ethiopia survey, according  to BRGI, BRGP method estimators")
}



options(digits=7)
```
\end{table}


```{r, echo=FALSE, cache=F,eval=F,include=F}
var.labels3 = c(V3="estimate (sd) [LIC, UIC]",
V4="estimate [LIC, UIC]",
V5="estimate [LIC, UIC]",
V2="STH type",
V1="Model")
label(Prev.IP.text) = as.list( var.labels3[match(names(Prev.IP.text), names(var.labels3))] )


Prev.IP.text2<-subset(Prev.IP.text,select = -c(V2))




if(knitr::is_latex_output()) {Prev.IP.text2%>% kableExtra::kable( booktabs = T, row.names = FALSE, col.names= label(Prev.IP.text2), caption = "STHs Prevalence, KK Sensitivity, KK Specificity estimates for Ethiopia survey, according to BRGI, BRGP, MoMI, MoMP, and Naive GS exact method estimators")%>%kableExtra::kable_styling(latex_options = c("striped","HOLD_position"),font_size = 10)%>% kableExtra::add_header_above(c("Estimator"=1,"Prevalence" = 1, "Sensitivity" = 1, "Specificity" = 1))%>%
kableExtra::pack_rows("Ascaris", 1, 5)%>%
  kableExtra::pack_rows("Hookworm", 6, 10)%>%
  kableExtra::pack_rows("Trichuris", 11, 15)%>%
  kableExtra::pack_rows("Schistosoma", 16, 20)%>% kableExtra::add_footnote(c("sd: standard deviation, LIC: Lower Interval Credible, UIC: Upper Interval Credible, GS: Gold Standard"), notation="none") 
} else if (!knitr::is_latex_output() ) {
Prev.IP.text2%>% flextable::flextable()%>%autofit()%>%flextable::set_caption("STHs Prevalence, KK Sensitivity, KK Specificity estimates for Ethiopia survey, according to BRGI, BRGP, MoMI, MoMP, and Naive GS exact method estimators")
}



options(digits=7)

```









```{r c12a12, fig.cap=" Zip Plot Comparing Simulation Results for BRGI, and BRGP True Prevalence Value 0.01, CP=0.90/0.95", eval=TRUE, include=T, fig.height=9, eval=F, include=F}
## Zip Plot Comparing Simulation Results for BRGI, and BRGP True Prevalence Value 0.01/0.03 

library(ggpubr)

ggarrange(a1,a2,labels = c("A", "B"),ncol = 1, nrow = 2)


```
 
```{r c14a12, fig.cap=" Zip Plot Comparing Simulation Results for BRGI, and BRGP True Prevalence Value 0.03, CP=0.90/0.95.", eval=TRUE, include=T, fig.height=9, eval=F, include=F}


ggarrange(b1,b2,labels = c("A", "B"),ncol = 1, nrow = 2)
```









```{r}
gridd<-expand.grid(prev.STH=c(0.1,0.2),schools=c(10,20),n.days=c(1,2 ), n.slide=c(1,2 ),pooln1=10, CV.i=1.5,mu=1000, CV.d=0.75,   pooln2=25, CV.d.10=0.6,CV.d.25=0.5, CV.s=0.25, plotss=FALSE, TPR=0.88*0.88,TNR=0.97*0.97, n.s=100, misclasifica=FALSE)

gridd$nnn=gridd$schools*gridd$n.s

gridd$dataset<-1:nrow(gridd)

gridd$name<-paste0("Dataset: ", gridd$dataset,"Shools: ",gridd$schools,". STH Prev:",gridd$prev.STH,". Days:",gridd$n.days,". Slides:",gridd$n.slide)
gridd$daysXsample<-gridd$n.days*gridd$n.slide
gridd<-gridd[order(gridd$daysXsample),]

gridd<-gridd[order(gridd$prev.STH,gridd$schools,gridd$n.days,gridd$n.slide),]

gridd$scenario<-gridd$Scenario<-1:nrow(gridd)


gridd$Info_level<-ifelse(gridd$daysXsample==1,"Low",ifelse(gridd$daysXsample==2,"Low Medium",ifelse(gridd$daysXsample==3,"Medium",ifelse(gridd$daysXsample==4,"Medium High",ifelse(gridd$daysXsample==6,"High", ifelse(gridd$daysXsample==9,"Very High",NA))))))
 
grid.sim<-vector(mode='list', length=nrow(gridd))
for (ji in 1:nrow(gridd)) {
grid.sim[[ji]]<-gridd[ji,]
}
 
reps=1:100

gridd.print<-subset(gridd,select = -c(plotss,TPR,TNR, misclasifica,dataset,scenario,Info_level, pooln2))

```



```{r ch1020_TabDGM}
library(dplyr)
gridd.print<-subset(gridd,select =c(Scenario,prev.STH,schools, n.days,n.slide, mu,pooln1,CV.i,CV.d,CV.d.10,CV.s,n.s,nnn))
 
colnames(gridd.print)<-c("Scenario",
                           "$\\pi_{schools}$",
                           "$n_{schools}$",
                           "$n_{days}$",
                           "$n_{slides}$",
                           "$\\mu$",                           
                           "$\\eta$",
                           "$CV_i$",
                           "$CV_d^{1}$",
                           "$CV_d^{10}$",
                           "$CV_s$",
                           "n.s",
                           "N")
 



if(knitr::is_latex_output()) {gridd.print%>%kableExtra::kable(row.names = FALSE,caption = "Additional considered scenarios as data generating mechanism for the simulation study. Prevalence 0.1 and 0.2", escape = F)%>% kableExtra::add_header_above(c("Scenarios" = 5, "Assumptions" = 2, "Agregattion parameters" = 4, "Sample size" = 2))%>% kableExtra::kable_styling(font_size = 8, latex_options = c("striped","HOLD_position"))%>% kableExtra::add_footnote(escape = F, c("$\\pi_{schools}$: true prevalence for each school, $n_{schools}$ is the number of schools; $n_{days}$ is the number of $days$ where test are conducted, $n_{slides}$ is the number $slides$ collected for each day; $\\mu$  is the population mean EPG, $\\eta$ is the the number of subjects for each pool; $CV_i$, $CV_d^{1}$, $CV_d^{10}$, $CV_s$ are the Coefficient of Variation related to subject, related to $days$ in each subject sample, related to days in each pool sample, related to each $slide$, respectively;  $n.s$ is the number of subjects per $schools$, and $N$ is the total number of subjects in the whole population."), threeparttable = TRUE,  notation="none") 

} else if (!knitr::is_latex_output() ) {
gridd.print%>% flextable::flextable()%>%autofit()%>%flextable::set_caption("Additional considered scenarios as data generating mechanism for the simulation study. Prevalence 0.1 and 0.2")
}


 
```



 


```{r ch1020_res, eval=F,include=F }
 
results3<-fit_models(dataDF=TEMPO, gridsDF=grid.sim,   model="Method of Moment")
results4<-fit_models(dataDF=TEMPO, gridsDF=grid.sim,   model="Method of Moment Pool")

result1<-results1[[1]]

result2<-results2[[1]]

result3<-results3[[1]]
result4<-results4[[1]]

 
```




```{r ch1020_c9} 

names(result1)<-c(result1[[1]][["Scenario name"]][1],
                 result1[[2]][["Scenario name"]][1],
                 result1[[3]][["Scenario name"]][1],
                 result1[[4]][["Scenario name"]][1],
                 result1[[5]][["Scenario name"]][1],
                 result1[[6]][["Scenario name"]][1],
                 result1[[7]][["Scenario name"]][1],
                 result1[[8]][["Scenario name"]][1],
                 result1[[9]][["Scenario name"]][1],
                 result1[[10]][["Scenario name"]][1],
                 result1[[11]][["Scenario name"]][1],
                 result1[[12]][["Scenario name"]][1],
                 result1[[13]][["Scenario name"]][1],
                 result1[[14]][["Scenario name"]][1],
                 result1[[15]][["Scenario name"]][1],
                 result1[[16]][["Scenario name"]][1])
names(result2)<-c(result2[[1]][["Scenario name"]][1],
                  result2[[2]][["Scenario name"]][1],
                  result2[[3]][["Scenario name"]][1],
                  result2[[4]][["Scenario name"]][1],
                  result2[[5]][["Scenario name"]][1],
                  result2[[6]][["Scenario name"]][1],
                  result2[[7]][["Scenario name"]][1],
                  result2[[8]][["Scenario name"]][1],
                  result2[[9]][["Scenario name"]][1],
                  result2[[10]][["Scenario name"]][1],
                  result2[[11]][["Scenario name"]][1],
                  result2[[12]][["Scenario name"]][1],
                  result2[[13]][["Scenario name"]][1],
                  result2[[14]][["Scenario name"]][1],
                  result2[[15]][["Scenario name"]][1],
                  result2[[16]][["Scenario name"]][1])
names(result3)<-c(result3[[1]][["Scenario name"]][1],
                  result3[[2]][["Scenario name"]][1],
                  result3[[3]][["Scenario name"]][1],
                  result3[[4]][["Scenario name"]][1],
                  result3[[5]][["Scenario name"]][1],
                  result3[[6]][["Scenario name"]][1],
                  result3[[7]][["Scenario name"]][1],
                  result3[[8]][["Scenario name"]][1],
                  result3[[9]][["Scenario name"]][1],
                  result3[[10]][["Scenario name"]][1],
                  result3[[11]][["Scenario name"]][1],
                  result3[[12]][["Scenario name"]][1],
                  result3[[13]][["Scenario name"]][1],
                  result3[[14]][["Scenario name"]][1],
                  result3[[15]][["Scenario name"]][1],
                  result3[[16]][["Scenario name"]][1])
names(result4)<-c(result4[[1]][["Scenario name"]][1],
                  result4[[2]][["Scenario name"]][1],
                  result4[[3]][["Scenario name"]][1],
                  result4[[4]][["Scenario name"]][1],
                  result4[[5]][["Scenario name"]][1],
                  result4[[6]][["Scenario name"]][1],
                  result4[[7]][["Scenario name"]][1],
                  result4[[8]][["Scenario name"]][1],
                  result4[[9]][["Scenario name"]][1],
                  result4[[10]][["Scenario name"]][1],
                  result4[[11]][["Scenario name"]][1],
                  result4[[12]][["Scenario name"]][1],
                  result4[[13]][["Scenario name"]][1],
                  result4[[14]][["Scenario name"]][1],
                  result4[[15]][["Scenario name"]][1],
                  result4[[16]][["Scenario name"]][1])
 
for (kk in 1:16) {
  colnames(result1[[kk]])<-colnames(result2[[kk]])<-c("Scenario name",
"prev.STH",
"Scenario",
"Dataset n",
"Rep n",
"model",
"theta.sd",
"theta",
"theta.var",
"theta.se",
"LIC",
"UIC",
"iHPD90",
"uHPD90",
"iHPD95",
"uHPD95",
"n")

}

 


results.merged<-c(result1,result2,result3,result4)
relhaz2 <- do.call(
  rbind.data.frame,
  results.merged
)

row.names(relhaz2) <- NULL


relhaz2$prev.STH<-as.numeric(relhaz2$prev.STH)
relhaz2$theta.sd<-as.numeric(relhaz2$theta.sd)
relhaz2$theta<-as.numeric(relhaz2$theta)
relhaz2$theta.se<-as.numeric(relhaz2$theta.se)
relhaz2$theta.var<-as.numeric(relhaz2$theta.var)
relhaz2$LIC<-as.numeric(relhaz2$LIC)
relhaz2$UIC<-as.numeric(relhaz2$UIC)
relhaz2$iHPD90<-as.numeric(relhaz2$iHPD90)
relhaz2$uHPD90<-as.numeric(relhaz2$uHPD90)
relhaz2$iHPD95<-as.numeric(relhaz2$iHPD95)
relhaz2$uHPD95<-as.numeric(relhaz2$uHPD95)
relhaz2$n<-as.numeric(relhaz2$n)
relhaz2$`Rep n`<-as.numeric(relhaz2$`Rep n`)

```



```{r ch1020_c10, tab.cap="Prevalence check-up"} 

relhaz2$model<-ifelse(relhaz2$model=="Bayesian Rogen-Gladen","BRGI",ifelse(relhaz2$model=="Bayesian Rogen-Gladen Pool","BRGP", ifelse(relhaz2$model=="Method of Moment","MoM Ind",ifelse(relhaz2$model=="Method of Moment Pool","MoM Pool",relhaz2$model))))


relhaz2$Schools<-ifelse(grepl("Shools: 10",relhaz2$`Scenario name`),10,20)
relhaz2$Days<-ifelse(grepl("Days:1",relhaz2$`Scenario name`),1,2)
relhaz2$Slides<-ifelse(grepl("Slides:1",relhaz2$`Scenario name`),1,2)
relhaz2$daysXslides<-relhaz2$Days*relhaz2$Slides


#chequear el orden de TP, y previas integraciones
prevalencias<-unique(relhaz2$prev.STH)



simm.all.HPD.95.10<- rsimsum::simsum(data =   subset(relhaz2,prev.STH==0.1), estvarname = "theta", se ="theta.se", true = 0.1, methodvar = "model", ci.limits = c("iHPD95", "uHPD95"),x = TRUE,ref = "BRGI", by =c("Schools", "Days","Slides"), control=list(level=0.95 ) )
simm.all.HPD.90.10<- rsimsum::simsum(data =   subset(relhaz2,prev.STH==0.1), estvarname = "theta", se ="theta.se", true = 0.1, methodvar = "model", ci.limits = c("iHPD90", "uHPD90"),x = TRUE,ref = "BRGI", by =c("Schools", "Days","Slides"), control=list(level=0.90 ) )
simm.all.HPD.95.20<- rsimsum::simsum(  data =   subset(relhaz2,prev.STH==0.2), estvarname = "theta", se ="theta.se", true = 0.2, methodvar = "model", ci.limits = c("iHPD95", "uHPD95"),x = TRUE,ref = "BRGI", by =c("Schools", "Days","Slides"), control=list(level=0.95 ) )
simm.all.HPD.90.20<- rsimsum::simsum(data =   subset(relhaz2,prev.STH==0.2), estvarname = "theta", se ="theta.se", true = 0.2, methodvar = "model", ci.limits = c("iHPD90", "uHPD90"),x = TRUE,ref = "BRGI", by =c("Schools", "Days","Slides"), control=list(level=0.90 ) )

#simm.all.HPD.95.1;simm.all.HPD.95.2
```



```{r ch1020_box1, fig.cap="Boxplot for model bias in each scenario and number of $days \\cdot slides$. The scenarios are ordered according to the average bias of each one; true prevalence = 0.1.", fig.height=8}
 

relhaz2$bias<-relhaz2$theta-relhaz2$prev.STH
 

ggplot(subset(relhaz2,prev.STH==0.1), aes(x=reorder(Scenario,bias,na.rm = TRUE),y=bias, pattern = as.factor(Schools), fill=as.factor(daysXslides))) +
  geom_boxplot(position="dodge",aes(fill=as.factor(daysXslides)))+geom_hline(yintercept=0, linetype="dashed", color = "black")+ facet_wrap(~model, ncol=1, scales = "free")+
  geom_point(size=0.2,alpha = 0.3)+ labs(x="Scenarios")+
  scale_fill_manual(name = "daysXslides", values = c("#FDECCD", "#BAE4B3", "#6BADD5")) +
  geom_boxplot_pattern(position = position_dodge(preserve = "single"), pattern_angle = 45, pattern_density = 0.01, pattern_spacing = 0.025, pattern_key_scale_factor = 0.6) +
  guides(pattern = guide_legend(override.aes = list(fill = "white")), fill = guide_legend(override.aes = list(pattern = "none")))+theme(legend.position="bottom", panel.background = element_blank(), axis.line = element_line(colour = "grey"), panel.grid.major = element_line(colour = "lightgray"),panel.grid.minor = element_line(colour = "lightgray"), 
panel.grid.major.y = element_blank())+labs(pattern=expression(n[schools]))+ylab("Bias")


```

```{r ch1020_box2, fig.cap="Boxplot for model bias for each scenario and number of $days$ x $slides$. The scenarios are ordered according to the average bias of each one; true prevalence = 0.2.", fig.height=8}

ggplot(subset(relhaz2,prev.STH==0.2), aes(x=reorder(Scenario,bias,na.rm = TRUE),y=bias, pattern = as.factor(Schools), fill=as.factor(daysXslides))) +
  geom_boxplot(position="dodge",aes(fill=as.factor(daysXslides)))+geom_hline(yintercept=0, linetype="dashed", color = "black")+ facet_wrap(~model, ncol=1, scales = "free")+
  geom_point(size=0.2,alpha = 0.3)+ labs(x="Scenarios")+
  scale_fill_manual(name = "daysXslides", values = c("#FDECCD", "#BAE4B3", "#6BADD5")) +
  geom_boxplot_pattern(position = position_dodge(preserve = "single"), pattern_angle = 45, pattern_density = 0.01, pattern_spacing = 0.025, pattern_key_scale_factor = 0.6) +
  guides(pattern = guide_legend(override.aes = list(fill = "white")), fill = guide_legend(override.aes = list(pattern = "none")))+theme(legend.position="bottom", panel.background = element_blank(), axis.line = element_line(colour = "grey"), panel.grid.major = element_line(colour = "lightgray"),panel.grid.minor = element_line(colour = "lightgray"), 
panel.grid.major.y = element_blank())+labs(pattern=expression(n[schools]))+ylab("Bias")

```




```{r ch1020_c11a, echo=FALSE} 

p.simm.all.HPD.95.1<-summary(simm.all.HPD.95.1)[["summ"]]
p.simm.all.HPD.95.1<-p.simm.all.HPD.95.1[p.simm.all.HPD.95.1$stat %in% c("bias",    "cover", "mse"  ),]
p.simm.all.HPD.95.1$stat<-ifelse(p.simm.all.HPD.95.1$stat=="cover","CP 95%",p.simm.all.HPD.95.1$stat)

p.simm.all.HPD.90.1<-summary(simm.all.HPD.90.1)[["summ"]]
p.simm.all.HPD.90.1<-p.simm.all.HPD.90.1[p.simm.all.HPD.90.1$stat=="cover",]
p.simm.all.HPD.90.1$stat<-ifelse(p.simm.all.HPD.90.1$stat=="cover","CP 90%",p.simm.all.HPD.90.1$stat)
p.simm.all.HPD.95.1<-rbind(p.simm.all.HPD.95.1,p.simm.all.HPD.90.1)

p.simm.all.HPD.95.1<-subset(p.simm.all.HPD.95.1,select=-c(lower,upper))
p.simm.all.HPD.95.1<-p.simm.all.HPD.95.1[order(p.simm.all.HPD.95.1$stat),]
p.simm.all.HPD.95.1$est<-ifelse((p.simm.all.HPD.95.1$stat=="CP 90%"|p.simm.all.HPD.95.1$stat=="CP 95%")&(grepl("MoM",p.simm.all.HPD.95.1$model)),NA,p.simm.all.HPD.95.1$est)
```


```{r ch1020_result1, echo=FALSE} 

pp.1<-p.simm.all.HPD.95.1%>%tidyr::pivot_wider(names_from = model, values_from = c(est,mcse))

pp.1<-pp.1[order(pp.1$Schools,pp.1$Days,pp.1$Slides),]
pp.1$Scenarios<-rep(1:(nrow(gridd)/2),each=4)

pp.1.scene<-subset(pp.1,select=c(stat,est_BRGI,est_BRGP,`est_MoM Ind`,`est_MoM Pool`))
pp.1.perf<-subset(pp.1,select=c(stat,Schools,Days,Slides,est_BRGI,mcse_BRGI,est_BRGP,mcse_BRGP,`est_MoM Ind`,`mcse_MoM Ind`,`est_MoM Pool`,`mcse_MoM Pool`))






if(knitr::is_latex_output()) {
  
colnames(pp.1.perf)<-c("Measures","$n_{schools}$","$n_{days}$","$n_{slides}$","est","mcse","est","mcse","est","mcse","est","mcse")
colnames(pp.1.scene)<-c("Measures","Estimates", "Estimates", "Estimates", "Estimates" )
  pp.1.scene%>%kableExtra::kable( caption = "Performance measure for prevalence=0.1, for each scenario by model", escape=T, booktabs = T, digits=5, format="latex")%>%kableExtra::kable_styling(latex_options = c("striped", "scale_down"),full_width =T) %>% kableExtra::add_header_above(c("Performance" = 1, "BRGI" = 1, "BRGP" = 1, "MoM Ind" = 1, "MoM Pool" = 1))%>%
  kableExtra::pack_rows("Scenario 1", 1, 4)%>%
  kableExtra::pack_rows("Scenario 2", 5, 8)%>%
  kableExtra::pack_rows("Scenario 3", 9, 12)%>%
  kableExtra::pack_rows("Scenario 4", 13, 16)%>%
  kableExtra::pack_rows("Scenario 5", 17, 20)%>%
  kableExtra::pack_rows("Scenario 6", 21, 24)%>%
  kableExtra::pack_rows("Scenario 7", 25, 28)%>%
  kableExtra::pack_rows("Scenario 8", 29, 32)
} else if (!knitr::is_latex_output() ) {
pp.1.scene%>% flextable::flextable()%>%autofit()%>%flextable::set_caption("Performance measure for prevalence=0.1, for each scenario by model")
}



```

 
  




```{r ch1020_c11b, echo=FALSE} 

p.simm.all.HPD.95.2<-summary(simm.all.HPD.95.2)[["summ"]]
p.simm.all.HPD.95.2<-p.simm.all.HPD.95.2[p.simm.all.HPD.95.2$stat %in% c("bias",    "cover", "mse"  ),]
p.simm.all.HPD.95.2$stat<-ifelse(p.simm.all.HPD.95.2$stat=="cover","CP 95%",p.simm.all.HPD.95.2$stat)

p.simm.all.HPD.90.2<-summary(simm.all.HPD.90.2)[["summ"]]
p.simm.all.HPD.90.2<-p.simm.all.HPD.90.2[p.simm.all.HPD.90.2$stat=="cover",]
p.simm.all.HPD.90.2$stat<-ifelse(p.simm.all.HPD.90.2$stat=="cover","CP 90%",p.simm.all.HPD.90.2$stat)
p.simm.all.HPD.95.2<-rbind(p.simm.all.HPD.95.2,p.simm.all.HPD.90.2)

p.simm.all.HPD.95.2<-subset(p.simm.all.HPD.95.2,select=-c(lower,upper))
p.simm.all.HPD.95.2<-p.simm.all.HPD.95.2[order(p.simm.all.HPD.95.2$stat),]
p.simm.all.HPD.95.2$est<-ifelse((p.simm.all.HPD.95.2$stat=="CP 90%"|p.simm.all.HPD.95.2$stat=="CP 95%")&(grepl("MoM",p.simm.all.HPD.95.2$model)),NA,p.simm.all.HPD.95.2$est)
```





```{r ch1020_result2, echo=FALSE} 

pp.2<-p.simm.all.HPD.95.2%>%tidyr::pivot_wider(names_from = model, values_from = c(est,mcse))
pp.2<-pp.2[order(pp.2$Schools,pp.2$Days,pp.2$Slides),]
pp.2$Scenarios<-rep((1+8):(nrow(gridd)/2+8),each=4)

pp.2.scene<-subset(pp.2,select=c(stat,est_BRGI,est_BRGP,`est_MoM Ind`,`est_MoM Pool`))
pp.2.perf<-subset(pp.2,select=c(stat,Schools,Days,Slides,est_BRGI,mcse_BRGI,est_BRGP,mcse_BRGP,`est_MoM Ind`,`mcse_MoM Ind`,`est_MoM Pool`,`mcse_MoM Pool`))









if(knitr::is_latex_output()) {
colnames(pp.2.perf)<-c("Measures","$n_{schools}$","$n_{days}$","$n_{slides}$","est","mcse","est","mcse","est","mcse","est","mcse")
  



colnames(pp.2.scene)<-c("Measures","Estimates", "Estimates", "Estimates", "Estimates" )
  pp.2.scene%>%kableExtra::kable(  caption = "Performance measure for prevalence=0.2, for each scenario by model",escape=T,  booktabs = T, format="latex", digits=5 )%>%kableExtra::kable_styling(latex_options = c("striped", "scale_down"),full_width = T)%>%kableExtra::add_header_above(c("Performance" = 1, "BRGI" = 1, "BRGP" = 1, "MoM Ind" = 1, "MoM Pool" = 1))%>%
  kableExtra::pack_rows("Scenario 9", 1, 4)%>%
  kableExtra::pack_rows("Scenario 10", 5, 8)%>%
  kableExtra::pack_rows("Scenario 11", 9, 12)%>%
  kableExtra::pack_rows("Scenario 12", 13, 16)%>%
  kableExtra::pack_rows("Scenario 13", 17, 20)%>%
  kableExtra::pack_rows("Scenario 14", 21, 24)%>%
  kableExtra::pack_rows("Scenario 15", 25, 28)%>%
  kableExtra::pack_rows("Scenario 16", 29,32)
} else if (!knitr::is_latex_output() ) {
pp.2.scene%>% flextable::flextable()%>%autofit()%>%flextable::set_caption("Performance measure for prevalence=0.2, for each scenario by model")
}



```



```{r regcoefplot, fig.cap="Models 1 and 1a, linear regression models for $\\pi$ bias using the DGM parameters and interaction as predictors; all models are included."}
relhaz3<-rbind(relhaz[,-23],relhaz2)

library(broom)
m1<-lm(bias~model+ Schools+ Days+ Slides+ prev.STH, data=relhaz3)
m2<-update(m1, . ~ . + model*Schools+model*Slides+model*Days, data=relhaz3)
library(dotwhisker)
dwplot(list(m1, m2))+scale_fill_Publication ()+ theme_Publication()+ geom_vline(xintercept = 0,color="grey", linetype = "dashed")
```

```{r m11a, results='asis', message=FALSE, warning=FALSE, verbose=FALSE}

#library(stargazer)
#stargazer(m1,m2, type="latex", title="Models 1 and 1a, linear regression models for bias using the DGM parameters and interaction as predictors; all models are included.", keep.stat="n", single.row=TRUE)
#stargazer , column.labels='Model 1 & Model 1a', font.size="small")`
```

```{r, include=F, eval=F}
# \begin{table}[!htbp] \centering 
#   \caption{Models 1 and 1a, linear regression models for bias using the DGM parameters and interaction as # predictors; all models are included.} 
#   \label{} 
# \begin{tabular}{@{\extracolsep{5pt}}lcc} 
# \\[-1.8ex]\hline 
# \hline \\[-1.8ex] 
#  & \multicolumn{2}{c}{\textit{Dependent variable:}} \\ 
# \cline{2-3} 
# \\[-1.8ex] & \multicolumn{2}{c}{Bias} \\ 
# \\[-1.8ex] & (Model 1) & (Model 1a)\\ 
# \hline \\[-1.8ex] 
#  modelBRGP & $-$0.005$^{***}$ (0.001) & $-$0.004 (0.007) \\ 
#   modelMoM Ind & 0.169$^{***}$ (0.001) & 0.117$^{***}$ (0.007) \\ 
#   modelMoM Pool & 0.189$^{***}$ (0.001) & 0.147$^{***}$ (0.007) \\ 
#   Schools & $-$0.0001 (0.0001) & $-$0.00003 (0.0002) \\ 
#   Days & 0.011$^{***}$ (0.001) & 0.001 (0.002) \\ 
#   Slides & 0.008$^{***}$ (0.001) & 0.001 (0.002) \\ 
#   prev.STH & 0.556$^{***}$ (0.007) & 0.556$^{***}$ (0.007) \\ 
#   modelBRGP:Schools &  & $-$0.0001 (0.0003) \\ 
#   modelMoM Ind:Schools &  & $-$0.0001 (0.0003) \\ 
#   modelMoM Pool:Schools &  & $-$0.00002 (0.0003) \\ 
#   modelBRGP:Slides &  & 0.0002 (0.003) \\ 
#   modelMoM Ind:Slides &  & 0.015$^{***}$ (0.003) \\ 
#   modelMoM Pool:Slides &  & 0.011$^{***}$ (0.003) \\ 
#   modelBRGP:Days &  & 0.0004 (0.003) \\ 
#   modelMoM Ind:Days &  & 0.021$^{***}$ (0.003) \\ 
#   modelMoM Pool:Days &  & 0.018$^{***}$ (0.003) \\ 
#   Constant & $-$0.076$^{***}$ (0.003) & $-$0.053$^{***}$ (0.005) \\ 
#  \hline \\[-1.8ex] 
# Observations & 12,800 & 12,800 \\ 
# \hline 
# \hline \\[-1.8ex] 
# \textit{Note:}  & \multicolumn{2}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\ 
# \end{tabular} 
# \end{table} 

```



```{r}

Prev.IP[(Prev.IP$model=='BRGI'| Prev.IP$model=='BRGP'),c(1,6:11)][1:6,]%>% kableExtra::kable( escape=T,booktabs = T, row.names = FALSE, col.names= label(Prev.IP[(Prev.IP$model=='BRGI'| Prev.IP$model=='BRGP'),c(1,6:11)]),digits=4, caption = "KK Sensitivity, KK Specificity estimates for Ethiopia survey, according  to BRGI, BRGP method estimators")%>%kableExtra::kable_styling(position = "center", latex_options = c("striped","HOLD_position"),font_size = 9)%>% 
  kableExtra::add_header_above(c( "Estimator" = 1,"Sensitivity" = 3, "Specificity" = 3))%>%
  kableExtra::pack_rows("Ascaris", 1, 2)%>%
  kableExtra::pack_rows("Hookworm", 3, 4)%>%
  kableExtra::pack_rows("Trichuris", 5, 6)%>%
   kableExtra::add_footnote(c("Est: Estimate, sd: standard deviation, LIC: Lower Interval Credible, \n UIC: Upper Interval Credible"),   notation="none") 


```


```{r regcoefplot2, fig.cap="Models 2 and 2a, Linear regression models for $\\pi$ bias using the DGM parameters and interaction as predictors; only the Bayesian models are included.", fig.height=5, fig.width=8}
relhaz3.BR<-subset(relhaz3,model=="BRGP"|model=="BRGI")
m1.BR<-lm(bias~model+ Schools+ Days+ Slides+ prev.STH, data=relhaz3.BR)
m2.BR<-update(m1, . ~ . + model*Schools+model*Slides+model*Days, data=relhaz3.BR)
dwplot(list(m1.BR, m2.BR))+scale_fill_Publication ()+ theme_Publication()+ geom_vline(xintercept = 0,color="grey", linetype = "dashed")
```

```{r regcoefplot3, fig.cap="Models 3 and 3a, linear regression models for $\\pi$ bias using DGM parameters and interaction as predictors; only the MoM are included.", fig.height=5, fig.width=8}
relhaz3.MoM<-subset(relhaz3,model=="MoM Ind"|model=="MoM Pool")
m1.MoM<-lm(bias~model+ Schools+ Days+ Slides+ prev.STH, data=relhaz3.MoM)
m2.MoM<-update(m1, . ~ . + model*Schools+model*Slides+model*Days, data=relhaz3.MoM)
dwplot(list(m1.MoM, m2.MoM))+scale_fill_Publication ()+ theme_Publication()+ geom_vline(xintercept = 0,color="grey", linetype = "dashed")
```

```{r}
df.p <- data.frame(Schools=c(10, 20),
                 Days=c(1, 2),
                 Slides=c(1,2),
                 prev.STH=c(0.01,0.03,0.1,0.2),
                 model=c("",""))
#unique(relhaz3.MoM$prev.STH)


newdata.MoM1 = data.frame(Schools=c(20),Days=c(1),Slides=c(1),prev.STH=c(0.01),model=c("MoM Pool"))
newdata.MoM2 = data.frame(Schools=c(20),Days=c(1),Slides=c(1),prev.STH=c(0.01),model=c("MoM Ind"))

#predict(m2.MoM, newdata.MoM1)
#predict(m2.MoM, newdata.MoM2)

newdata.BR1 = data.frame(Schools=c(20),Days=c(1),Slides=c(1),prev.STH=c(0.01),model=c("BRGP"))
newdata.BR2 = data.frame(Schools=c(20),Days=c(1),Slides=c(1),prev.STH=c(0.01),model=c("BRGI"))
#predict(m2.BR, newdata.BR1)
#predict(m2.BR, newdata.BR2)
#predict(m1.MoM, newdata2)

```


```{r ba_all1, fig.cap="Comparison of $\\hat \\pi$ estimators using Bland-Altman plot type between all models; true prevalence value 0.01.", eval=TRUE, include=T, fig.height=9}
autoplot(simm.all.HPD.95.1, type = "est_ba")+ggtitle("")+
  geom_point(   fill = "#7fc97f", size = .05,   alpha=0.1, stroke=NA)+scale_colour_Publication()+ theme_Publication()
```
 
```{r ba_all2, fig.cap="Comparison of $\\hat\\pi$ estimators using Bland-Altman plot type between all models; true prevalence value 0.03.", eval=TRUE, include=T, fig.height=9}
autoplot(simm.all.HPD.95.2, type = "est_ba")+ggtitle("")+
  geom_point(   fill = "#7fc97f", size = .05,   alpha=0.1, stroke=NA)+scale_colour_Publication()+ theme_Publication()
```

```{r ba_all3, fig.cap="Comparison of $\\hat\\pi$ estimators using Bland-Altman plot type between all models; true prevalence value 0.1.", eval=TRUE, include=T, fig.height=9}
autoplot(simm.all.HPD.95.10, type = "est_ba")+ggtitle("")+
  geom_point(  fill = "#7fc97f", size = .05,  alpha=0.1, stroke=NA)+scale_colour_Publication()+ theme_Publication()
```
 
```{r ba_all4, fig.cap="Comparison of the $\\hat\\pi$ estimators using Bland-Altman plot type between all models; true prevalence value 0.2.", eval=TRUE, include=T, fig.height=9}
autoplot(simm.all.HPD.95.20, type = "est_ba")+ggtitle("")+
  geom_point(   fill = "#7fc97f", size = 0.05,   alpha=0.1, stroke=NA)+scale_colour_Publication()+ theme_Publication()
```






```{r mcse1}


if(knitr::is_latex_output()) {
  
pp.1.perf<-pp.1.perf[order(pp.1.perf$Measures),]
  pp.1.perf[,-1]%>%kableExtra::kable(booktabs = T, escape=T, caption = "Performance measure for prevalence=0.01, for each scenario by model", digits=5) %>%kableExtra::kable_styling(latex_options = c("striped","HOLD_position"),full_width = F, font_size = 7.5) %>% kableExtra::add_header_above(c( "Scenarios" = 3, "BRGI" = 2, "BRGP" = 2, "MoM Ind" = 2, "MoM Pool" = 2))   %>%kableExtra::pack_rows("Bias", 1, 8)%>%kableExtra::pack_rows("CP 90%", 9, 16)%>%kableExtra::pack_rows("CP 95%", 17, 24)%>%kableExtra::pack_rows("mse", 25, 32)

} else if (!knitr::is_latex_output() ) {
pp.1.perf[,-1]%>% flextable::flextable()%>%autofit()%>%flextable::set_caption("Performance measure for prevalence=0.01, for each scenario by model")
}



```



```{r mcse2}




if(knitr::is_latex_output()) {
pp.2.perf<-pp.2.perf[order(pp.2.perf$Measures),]
  
  pp.2.perf[,-1]%>%kableExtra::kable( booktabs = T, escape=T, caption = "Performance measure for prevalence=0.03, for each scenario by model", digits=5) %>%kableExtra::kable_styling(latex_options = c("striped","HOLD_position"),full_width = F, font_size = 7.5) %>% kableExtra::add_header_above(c("Scenarios" = 3, "BRGI" = 2, "BRGP" = 2, "MoM Ind" = 2, "MoM Pool" = 2))%>%kableExtra::pack_rows("Bias", 1, 8)%>%kableExtra::pack_rows("CP 90%", 9, 16)%>%kableExtra::pack_rows("CP 95%", 17, 24)%>%kableExtra::pack_rows("mse", 25, 32)
} else if (!knitr::is_latex_output() ) {
pp.2.perf[,-1]%>% flextable::flextable()%>%autofit()%>%flextable::set_caption("Performance measure for prevalence=0.03, for each scenario by model")
}


```

